export interface ServiceDetail {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  icon: string;
  what: string;
  whyUs: string[];
  metrics: { value: string; label: string }[];
  how: { title: string; desc: string }[];
  techStack: string[];
  benefits: string[];
  caseStudy: {
    title: string;
    challenge: string;
    result: string;
    metric: string;
  };
  faq: { q: string; a: string }[];
}

export const servicesData: ServiceDetail[] = [
  {
    slug: "web-development",
    title: "Web Development",
    tagline: "High-performance websites that convert",
    description:
      "We build blazing-fast, SEO-optimized websites and web applications using Next.js, React, and modern frameworks. Every site is engineered for performance, accessibility, and conversion.",
    icon: "Code2",
    what: "From corporate websites to complex web applications, we deliver production-ready solutions with sub-second load times, responsive design, and clean architecture. We specialize in Next.js and React — the same stack powering Netflix, Notion, and Vercel.",
    whyUs: [
      "Sub-second page loads with server-side rendering and static generation",
      "SEO-first architecture with structured data and Core Web Vitals optimization",
      "Component-driven design systems that ensure consistency at scale",
      "CMS integration so your team can update content without developers",
    ],
    metrics: [
      { value: "0.8s", label: "Avg. Load Time" },
      { value: "95+", label: "Lighthouse Score" },
      { value: "40+", label: "Sites Delivered" },
      { value: "3x", label: "Avg. Traffic Growth" },
    ],
    how: [
      { title: "Discovery & IA", desc: "We map your content, user flows, and technical requirements into a clear information architecture." },
      { title: "Design & Prototype", desc: "Interactive Figma prototypes with mobile-first responsive design — you approve before we code." },
      { title: "Development", desc: "Component-driven TypeScript development with Next.js, TailwindCSS, and automated testing." },
      { title: "Optimization", desc: "Core Web Vitals tuning, image optimization, lazy loading, and performance benchmarking." },
      { title: "SEO & Launch", desc: "Schema markup, sitemap, meta tags, analytics setup — then deploy to Vercel or your infrastructure." },
      { title: "Support & Growth", desc: "Ongoing maintenance, security updates, feature additions, and performance monitoring." },
    ],
    techStack: ["Next.js", "React", "TypeScript", "TailwindCSS", "Vercel", "Sanity CMS", "Framer Motion", "PostgreSQL"],
    benefits: [
      "Sub-second page loads with SSR/SSG",
      "SEO-optimized from the ground up",
      "Responsive across all devices and browsers",
      "CMS integration for easy content updates",
      "Accessibility compliance (WCAG 2.1 AA)",
      "Performance monitoring and alerting",
    ],
    caseStudy: {
      title: "Enterprise Corporate Website Rebuild",
      challenge: "A manufacturing company needed their legacy WordPress site rebuilt with modern performance standards and multilingual support.",
      result: "Delivered a Next.js site with sub-0.8s load times, 12 language variants, and Sanity CMS — resulting in 300% organic traffic increase in 6 months.",
      metric: "300% traffic increase",
    },
    faq: [
      { q: "How long does a typical website project take?", a: "A standard corporate website takes 3-5 weeks. Complex web applications with custom features take 6-12 weeks depending on scope and integrations required." },
      { q: "Do you provide ongoing maintenance?", a: "Yes. We offer monthly maintenance packages covering security updates, performance monitoring, content changes, and feature enhancements." },
      { q: "Can you migrate our existing website?", a: "Absolutely. We handle full migrations from WordPress, Wix, Squarespace, or custom platforms — preserving SEO equity and redirecting all URLs." },
    ],
  },
  {
    slug: "software-development",
    title: "Software Development",
    tagline: "Enterprise-grade systems built to scale",
    description:
      "Custom software solutions engineered for performance, security, and scalability. From complex business logic to distributed systems, we build software that handles real-world complexity.",
    icon: "Cpu",
    what: "We design and build custom software systems that solve complex business problems — ERPs, CRMs, workflow engines, APIs, microservices, and everything in between. Our architecture-first approach ensures your system scales with your business.",
    whyUs: [
      "Architecture-first approach — we design for scale before writing a line of code",
      "Full-stack engineering team with backend, frontend, DevOps, and QA",
      "CI/CD pipelines and automated testing built into every project",
      "Zero-downtime deployments and 99.9% uptime SLAs",
    ],
    metrics: [
      { value: "99.9%", label: "Uptime SLA" },
      { value: "50+", label: "Systems Built" },
      { value: "10M+", label: "Users Served" },
      { value: "24/7", label: "Monitoring" },
    ],
    how: [
      { title: "Business Analysis", desc: "We document your processes, identify pain points, and map requirements to technical specifications." },
      { title: "System Architecture", desc: "Scalable architecture design — monolith, microservices, or event-driven — based on your needs." },
      { title: "API-First Development", desc: "Clean, documented APIs that power your frontend, mobile apps, and third-party integrations." },
      { title: "Database Design", desc: "Optimized schema design, indexing strategy, and data migration planning for production workloads." },
      { title: "Testing & QA", desc: "Unit tests, integration tests, load testing, and security testing before every release." },
      { title: "Deployment & DevOps", desc: "CI/CD pipelines, containerization, infrastructure as code, and staged rollouts." },
    ],
    techStack: ["Node.js", "Python", "PostgreSQL", "Redis", "Docker", "AWS", "Kubernetes", "GraphQL"],
    benefits: [
      "Scalable architecture that grows with your business",
      "Comprehensive automated test coverage",
      "Full API documentation with OpenAPI/Swagger",
      "24/7 monitoring with PagerDuty alerting",
      "Security-first with encryption at rest and in transit",
      "Zero-downtime deployment strategy",
    ],
    caseStudy: {
      title: "Logistics Management Platform",
      challenge: "A logistics company needed to replace 5 disconnected spreadsheets and legacy tools with a unified system handling 10,000+ daily shipments.",
      result: "Built a custom platform with real-time tracking, automated routing, and driver management — reducing operational costs by 40%.",
      metric: "40% cost reduction",
    },
    faq: [
      { q: "Do you work with legacy systems?", a: "Yes. We regularly modernize legacy systems through incremental migration, API wrapping, or full rebuilds — always minimizing business disruption." },
      { q: "How do you handle data security?", a: "Security is built into every layer: encrypted data at rest and in transit, role-based access control, regular security audits, and compliance with relevant standards." },
      { q: "Can you integrate with our existing tools?", a: "Yes — we build integration layers for Salesforce, SAP, HubSpot, Stripe, and any tool with an API. Custom webhooks and event-driven architecture keep everything in sync." },
    ],
  },
  {
    slug: "ai-development",
    title: "AI Development",
    tagline: "Custom AI that gives you an unfair advantage",
    description:
      "Custom AI/ML models, LLM integrations, intelligent chatbots, and AI-powered features that transform how your business operates and competes.",
    icon: "BrainCircuit",
    what: "We build production-grade AI systems — from fine-tuned LLMs and RAG pipelines to computer vision and predictive analytics. Not demos, not prototypes — real AI that works in production with error handling, monitoring, and continuous improvement.",
    whyUs: [
      "Production-grade AI, not just demos — robust error handling and fallback systems",
      "Cost-optimized inference with model routing and caching strategies",
      "RAG architecture for knowledge-grounded, hallucination-resistant AI",
      "Fine-tuning capabilities for domain-specific performance",
    ],
    metrics: [
      { value: "15+", label: "AI Projects Live" },
      { value: "95%", label: "Accuracy Rate" },
      { value: "60%", label: "Avg. Cost Savings" },
      { value: "<2s", label: "Response Time" },
    ],
    how: [
      { title: "AI Opportunity Audit", desc: "We assess where AI can deliver real ROI in your business — not just where it's trendy." },
      { title: "Data Pipeline", desc: "Clean, structure, and prepare your data for model training or RAG retrieval systems." },
      { title: "Model Selection", desc: "Choose the right model (GPT-4, Claude, Llama, custom) based on accuracy, cost, and latency requirements." },
      { title: "RAG / Fine-Tuning", desc: "Build retrieval-augmented generation systems or fine-tune models on your proprietary data." },
      { title: "API & Integration", desc: "Production APIs with rate limiting, caching, fallbacks, and seamless integration with your existing stack." },
      { title: "Monitor & Improve", desc: "Continuous evaluation, A/B testing, prompt optimization, and cost monitoring post-launch." },
    ],
    techStack: ["OpenAI GPT-4", "Claude", "LangChain", "Python", "FastAPI", "Pinecone", "Hugging Face", "ChromaDB"],
    benefits: [
      "Production-ready AI with robust error handling",
      "Custom models trained on your proprietary data",
      "Cost-optimized inference pipelines",
      "Hallucination-resistant RAG architectures",
      "Real-time monitoring and evaluation dashboards",
      "Seamless integration with existing systems",
    ],
    caseStudy: {
      title: "AI-Powered Legal Document Analyzer",
      challenge: "A law firm needed to analyze thousands of contracts, extract key clauses, identify risks, and generate summary reports.",
      result: "Built an AI platform using GPT-4 and custom extraction models that saves lawyers 15+ hours per week with 95% accuracy.",
      metric: "15 hrs/week saved",
    },
    faq: [
      { q: "Can you integrate AI into our existing product?", a: "Absolutely. We specialize in adding AI capabilities to existing systems — chatbots, smart search, content generation, data analysis, and more." },
      { q: "How do you manage AI costs?", a: "We optimize from day one: caching frequent queries, model routing (cheaper models for simple tasks), batching requests, and token optimization." },
      { q: "What about data privacy?", a: "We can deploy models on your own infrastructure, use Azure OpenAI for data isolation, or implement strict data processing agreements with third-party providers." },
    ],
  },
  {
    slug: "mvp-development",
    title: "MVP Development",
    tagline: "Idea to launch in weeks, not months",
    description:
      "We design, build, and ship investor-ready MVPs in 4-8 weeks with lean, scalable architecture that grows with you post-funding.",
    icon: "Rocket",
    what: "Your MVP needs to do three things: validate your hypothesis, impress investors, and be architecturally sound enough to scale. We deliver all three with a lean process that prioritizes speed without cutting corners on quality.",
    whyUs: [
      "4-8 week delivery — from blank canvas to live product",
      "Investor-grade code quality and architecture documentation",
      "Scalable foundation that won't need a rewrite at Series A",
      "Post-MVP support: we stay as your technical partner through growth",
    ],
    metrics: [
      { value: "4–8", label: "Weeks to Launch" },
      { value: "25+", label: "MVPs Shipped" },
      { value: "80%", label: "Funded After MVP" },
      { value: "$0", label: "Rewrites Needed" },
    ],
    how: [
      { title: "Rapid Discovery", desc: "A 2-3 hour workshop to define your core hypothesis, target user, and must-have features." },
      { title: "Feature Prioritization", desc: "MoSCoW method to identify the 20% of features that deliver 80% of value." },
      { title: "Design Sprint", desc: "1-week UI/UX sprint producing interactive prototypes for key user flows." },
      { title: "Agile Build", desc: "2-week development sprints with live demos — you see progress in real-time." },
      { title: "User Testing", desc: "Real user feedback sessions, bug fixes, and UX refinements before launch." },
      { title: "Launch & Handoff", desc: "Deployment, analytics setup, investor demo prep, and growth strategy handoff." },
    ],
    techStack: ["Next.js", "React", "Node.js", "PostgreSQL", "Stripe", "Vercel", "Supabase", "TailwindCSS"],
    benefits: [
      "Launch-ready in 4-8 weeks",
      "Investor-quality code and design",
      "Architecture designed for scale",
      "Full source code ownership",
      "Post-MVP technical support",
      "Pitch deck tech section assistance",
    ],
    caseStudy: {
      title: "HealthTech Patient Portal MVP",
      challenge: "A first-time founder needed an investor-ready telehealth MVP with patient scheduling, video calls, and HIPAA-compliant data handling.",
      result: "Shipped in 6 weeks. The founder raised a $1.2M seed round 3 months after launch, with investors citing the product quality as a key factor.",
      metric: "$1.2M seed raised",
    },
    faq: [
      { q: "What's included in an MVP?", a: "Core user flows, authentication, the key feature set, responsive design, basic analytics, and production deployment. We focus on the minimum viable feature set that proves your hypothesis." },
      { q: "Do we own the code?", a: "100%. You get full source code ownership, a documented codebase, and deployment access. No lock-in, no licensing." },
      { q: "What happens after the MVP?", a: "We can continue as your development partner for post-launch iteration, or hand off to your in-house team with a full onboarding session and documentation." },
    ],
  },
  {
    slug: "saas-development",
    title: "SaaS Development",
    tagline: "Multi-tenant platforms built for recurring revenue",
    description:
      "End-to-end SaaS platform engineering — multi-tenant architecture, billing systems, dashboards, APIs, and infrastructure built for scale.",
    icon: "Cloud",
    what: "We build SaaS platforms from zero to launch: multi-tenant data isolation, subscription billing with Stripe, role-based access, admin dashboards, API layers, and the infrastructure to support thousands of concurrent users.",
    whyUs: [
      "True multi-tenant architecture with proper data isolation",
      "Stripe billing integration with trial management and dunning",
      "White-label capable architecture from day one",
      "Admin dashboards with real-time usage analytics",
    ],
    metrics: [
      { value: "15+", label: "SaaS Platforms" },
      { value: "50K+", label: "End Users Served" },
      { value: "99.9%", label: "Uptime" },
      { value: "$0", label: "Billing Errors" },
    ],
    how: [
      { title: "Business Model Analysis", desc: "We map your pricing tiers, feature gates, user roles, and monetization strategy into the technical architecture." },
      { title: "Multi-Tenant Architecture", desc: "Shared database with row-level security, or dedicated databases for regulated industries — your choice." },
      { title: "Billing & Subscriptions", desc: "Stripe integration with trial periods, upgrades/downgrades, prorations, dunning, and revenue analytics." },
      { title: "Dashboard & Admin", desc: "User-facing dashboards and admin panels with real-time data, usage tracking, and tenant management." },
      { title: "API & Integrations", desc: "RESTful or GraphQL APIs for third-party integrations, webhooks, and future mobile app support." },
      { title: "Launch & Scale", desc: "Load testing, security audit, staged rollout, and auto-scaling infrastructure for growth." },
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "Redis", "AWS", "Docker", "Prisma"],
    benefits: [
      "True multi-tenant architecture",
      "Stripe-powered billing from day one",
      "Admin dashboard with tenant analytics",
      "API-first for third-party integrations",
      "Auto-scaling infrastructure",
      "White-label ready architecture",
    ],
    caseStudy: {
      title: "HR Management SaaS Platform",
      challenge: "An HR startup needed a multi-tenant platform with employee management, payroll integration, leave tracking, and performance reviews for SMBs.",
      result: "Built and launched in 10 weeks. Now serving 50+ companies with 2,000+ active employees. MRR grew 40% month-over-month for the first 6 months.",
      metric: "50+ companies onboarded",
    },
    faq: [
      { q: "Database per tenant or shared database?", a: "We typically recommend shared database with row-level security for cost efficiency, but design per-tenant isolation for regulated industries like healthcare or finance." },
      { q: "How do you handle billing edge cases?", a: "Stripe handles the heavy lifting. We implement trial management, proration, failed payment dunning, plan switching, and usage-based billing with proper webhook handling." },
      { q: "Can the platform be white-labeled?", a: "Yes — we architect for white-labeling from day one: custom domains, theming, branding, and email templates per tenant." },
    ],
  },
  {
    slug: "ai-automations",
    title: "AI Automations",
    tagline: "Automate workflows and save hours daily",
    description:
      "Intelligent workflow automation with AI agents, custom GPTs, and integration platforms that eliminate repetitive work and scale your operations.",
    icon: "Bot",
    what: "We build automation systems that combine AI intelligence with workflow orchestration. From customer support bots to data processing pipelines to multi-step AI agents — we automate the work that's eating your team's time.",
    whyUs: [
      "AI-powered decision-making, not just simple if/then rules",
      "Visual workflow builders your non-technical team can modify",
      "Error handling and human-in-the-loop fallback for edge cases",
      "Monitoring dashboards showing ROI and time saved per automation",
    ],
    metrics: [
      { value: "80%", label: "Avg. Time Saved" },
      { value: "24/7", label: "Always Running" },
      { value: "100+", label: "Workflows Built" },
      { value: "0", label: "Errors Missed" },
    ],
    how: [
      { title: "Workflow Audit", desc: "Map your current manual processes and identify the highest-ROI automation opportunities." },
      { title: "Agent Design", desc: "Design AI agent behavior, decision trees, prompt chains, and fallback logic." },
      { title: "Platform Setup", desc: "Configure n8n, Make, or custom orchestration connecting all your tools and data sources." },
      { title: "AI Integration", desc: "Plug in GPT-4, Claude, or custom models for intelligent classification, extraction, and generation." },
      { title: "Testing", desc: "Run against real data with edge cases. Build error handling and human escalation paths." },
      { title: "Deploy & Train", desc: "Go live with monitoring dashboards and train your team to manage automations independently." },
    ],
    techStack: ["n8n", "OpenAI GPT-4", "LangChain", "Make", "Zapier", "Slack API", "Python", "Airtable"],
    benefits: [
      "80%+ reduction in manual repetitive work",
      "24/7 operation without human supervision",
      "Robust error handling and escalation paths",
      "Easy to modify without developer help",
      "ROI tracking and performance dashboards",
      "Integration with 500+ tools and platforms",
    ],
    caseStudy: {
      title: "E-Commerce Order Processing Automation",
      challenge: "A D2C brand was manually processing 200+ orders daily, syncing inventory across 3 channels, and handling customer support tickets.",
      result: "Built an AI automation suite that handles order processing, inventory sync, and first-line support — reducing manual work by 80% and response time from hours to minutes.",
      metric: "80% manual work eliminated",
    },
    faq: [
      { q: "What kind of tasks can be automated?", a: "Email triage, data entry, report generation, customer support, social media, lead qualification, invoice processing, inventory management — almost any repetitive workflow." },
      { q: "Do we need technical staff to maintain automations?", a: "No. We build with visual interfaces and documentation so non-technical team members can manage, modify, and extend automations." },
      { q: "How do you handle errors in automations?", a: "Every automation includes error detection, retry logic, human escalation alerts, and audit logging. Nothing fails silently." },
    ],
  },
  {
    slug: "seo",
    title: "SEO",
    tagline: "Data-driven organic growth that compounds",
    description:
      "Technical SEO, on-page optimization, content strategy, and Core Web Vitals tuning that delivers measurable, sustainable organic traffic growth.",
    icon: "Search",
    what: "We treat SEO as engineering, not guesswork. Our approach combines technical site optimization, content architecture, structured data implementation, and performance tuning to build organic traffic that compounds month over month.",
    whyUs: [
      "Engineering-led SEO — we fix root causes, not symptoms",
      "Core Web Vitals obsessed — we optimize what Google actually measures",
      "Schema markup specialists — rich results and knowledge panels",
      "Transparent reporting with actual metrics, not vanity numbers",
    ],
    metrics: [
      { value: "3x", label: "Avg. Traffic Growth" },
      { value: "95+", label: "Lighthouse Scores" },
      { value: "Top 3", label: "Avg. SERP Position" },
      { value: "200%", label: "Avg. Lead Increase" },
    ],
    how: [
      { title: "Technical Audit", desc: "Comprehensive crawl analysis, indexation review, Core Web Vitals assessment, and competitor benchmarking." },
      { title: "Architecture Strategy", desc: "URL structure optimization, internal linking strategy, and content hierarchy mapping." },
      { title: "On-Page Optimization", desc: "Title tags, meta descriptions, heading structure, content optimization, and image alt text across all pages." },
      { title: "Schema Markup", desc: "Structured data implementation for Organization, Service, FAQ, Article, and Review schemas." },
      { title: "Content Strategy", desc: "Keyword mapping, topic clusters, content calendar, and editorial guidelines for ongoing growth." },
      { title: "Monthly Reporting", desc: "Transparent monthly reports with traffic data, ranking changes, backlink growth, and actionable recommendations." },
    ],
    techStack: ["Google Search Console", "Ahrefs", "Screaming Frog", "PageSpeed Insights", "Schema.org", "GA4", "Semrush", "Next.js"],
    benefits: [
      "Measurable organic traffic growth",
      "Improved Core Web Vitals scores",
      "Rich results and featured snippets",
      "Transparent monthly reporting",
      "No black-hat techniques — sustainable growth only",
      "Compound growth that builds over time",
    ],
    caseStudy: {
      title: "SaaS Company Organic Growth",
      challenge: "A B2B SaaS startup had zero organic traffic and was fully dependent on paid ads for customer acquisition.",
      result: "Implemented technical SEO, content strategy, and schema markup. Organic traffic grew 340% in 6 months, becoming the #1 acquisition channel.",
      metric: "340% organic growth",
    },
    faq: [
      { q: "How long until we see results?", a: "Technical fixes show impact in 2-4 weeks. Content-driven growth typically shows meaningful results in 3-6 months, compounding over time." },
      { q: "Do you do link building?", a: "We focus on earning links through quality content, digital PR, and technical excellence — not paid link schemes that risk Google penalties." },
      { q: "Do you guarantee first page rankings?", a: "No one can honestly guarantee rankings — Google's algorithm considers hundreds of factors. We guarantee rigorous, data-driven execution that consistently delivers measurable traffic growth." },
    ],
  },
  {
    slug: "aieo",
    title: "AIEO",
    tagline: "Rank on AI search engines — the next frontier",
    description:
      "AI Engine Optimization — we structure your digital presence to be discoverable and recommended by ChatGPT, Gemini, Perplexity, and AI-powered search.",
    icon: "Sparkles",
    what: "AIEO is the practice of structuring your brand's digital footprint so AI assistants cite, recommend, and surface your business when users ask relevant questions. This is the next evolution of search, and we're among the first to offer dedicated AIEO services.",
    whyUs: [
      "Pioneer AIEO practitioners — we've studied how every major LLM retrieves and cites information",
      "Proprietary audit framework for measuring AI search visibility",
      "Complements traditional SEO — not a replacement, but the next layer",
      "Entity-first approach: build your brand as a knowledge entity AI can reference",
    ],
    metrics: [
      { value: "5+", label: "AI Engines Covered" },
      { value: "80%", label: "Mention Rate Lift" },
      { value: "#1", label: "AIEO Agency in PK" },
      { value: "100%", label: "Clients Retained" },
    ],
    how: [
      { title: "AI Visibility Audit", desc: "Test your brand's current presence across ChatGPT, Gemini, Perplexity, Claude, and Copilot." },
      { title: "Entity Optimization", desc: "Build your brand's entity profile across knowledge graphs, Wikipedia, Crunchbase, and structured data." },
      { title: "Content Restructuring", desc: "Reformat existing content for AI-friendly extraction — Q&A format, clear definitions, structured claims." },
      { title: "Citation Building", desc: "Get your brand cited in authoritative sources that LLMs index and reference." },
      { title: "Schema Enhancement", desc: "Advanced structured data that helps AI models understand your services, expertise, and authority." },
      { title: "Ongoing Monitoring", desc: "Track your brand's mentions and recommendations across AI platforms with monthly reporting." },
    ],
    techStack: ["ChatGPT", "Google Gemini", "Perplexity", "Claude", "Schema.org", "Knowledge Graphs", "Wikidata", "Ahrefs"],
    benefits: [
      "Appear in AI-generated answers and recommendations",
      "First-mover advantage in AI search optimization",
      "Complementary to traditional SEO — amplifies both",
      "Brand authority building across AI ecosystems",
      "Measurable improvement in AI search mentions",
      "Future-proof your digital marketing strategy",
    ],
    caseStudy: {
      title: "B2B SaaS AI Search Visibility",
      challenge: "A project management SaaS was invisible on AI search engines — competitors were being recommended instead when users asked 'best project management tools.'",
      result: "After 3 months of AIEO work, the brand appeared in ChatGPT and Gemini responses for 12 target queries, driving a new acquisition channel.",
      metric: "12 AI search queries ranked",
    },
    faq: [
      { q: "Is AIEO different from SEO?", a: "Yes. SEO optimizes for search engine crawlers and ranking algorithms. AIEO optimizes for how AI models retrieve, understand, and cite your content when generating answers for users." },
      { q: "Which AI engines do you optimize for?", a: "ChatGPT (OpenAI), Google Gemini, Perplexity, Claude (Anthropic), and Microsoft Copilot. Each has different data sources and citation patterns." },
      { q: "How do you measure AIEO results?", a: "We run structured queries across all major AI platforms weekly, tracking whether your brand is mentioned, recommended, or cited — and in what context." },
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    tagline: "Full-funnel campaigns that drive real ROI",
    description:
      "Paid advertising, social media strategy, email marketing, content marketing, and analytics-driven campaign optimization across all channels.",
    icon: "Megaphone",
    what: "We run full-funnel digital marketing campaigns that drive qualified leads and measurable revenue. From Google Ads and Meta campaigns to email sequences and content strategy — everything is data-driven and ROI-focused.",
    whyUs: [
      "ROI-focused — every campaign is measured by revenue generated, not vanity metrics",
      "Full-funnel capability — awareness, consideration, conversion, and retention",
      "Creative in-house — ad copy, design, video, and landing pages all under one roof",
      "Weekly optimization cycles — not set-and-forget campaign management",
    ],
    metrics: [
      { value: "420%", label: "Avg. ROAS" },
      { value: "50%", label: "Avg. CAC Reduction" },
      { value: "$2M+", label: "Ad Spend Managed" },
      { value: "3x", label: "Avg. Lead Growth" },
    ],
    how: [
      { title: "Market Research", desc: "Competitor analysis, audience research, keyword mapping, and channel opportunity assessment." },
      { title: "Strategy & Budget", desc: "Channel mix strategy, budget allocation, KPI definition, and campaign architecture planning." },
      { title: "Creative Development", desc: "Ad copy, banner designs, video scripts, and landing page design — all A/B test-ready." },
      { title: "Campaign Launch", desc: "Pixel setup, conversion tracking, audience targeting, and bid strategy implementation across all channels." },
      { title: "Optimization", desc: "Weekly A/B testing, audience refinement, creative rotation, and bid adjustments based on performance data." },
      { title: "Reporting & Scale", desc: "Weekly performance dashboards, monthly strategy reviews, and scaling playbooks for winning campaigns." },
    ],
    techStack: ["Google Ads", "Meta Ads", "LinkedIn Ads", "Mailchimp", "GA4", "Hotjar", "Semrush", "Canva"],
    benefits: [
      "Measurable ROI on every dollar spent",
      "Multi-channel attribution tracking",
      "In-house creative production",
      "Weekly optimization and A/B testing",
      "Transparent reporting with real metrics",
      "Scalable campaign frameworks",
    ],
    caseStudy: {
      title: "D2C Brand Growth Campaign",
      challenge: "A direct-to-consumer skincare brand needed to scale from $10K to $50K monthly revenue through digital channels.",
      result: "Implemented a full-funnel strategy across Meta, Google, and email. Achieved 420% ROAS and scaled to $65K monthly revenue in 4 months.",
      metric: "420% ROAS achieved",
    },
    faq: [
      { q: "What's your minimum ad budget?", a: "We recommend a minimum of $2,000/month in ad spend for meaningful data and optimization. Our management fee is separate and based on scope." },
      { q: "Do you handle creative too?", a: "Yes — ad copy, banner design, video ads, email templates, and landing page design are all part of our full-service offering." },
      { q: "How do you report results?", a: "Weekly Slack/email updates with key metrics. Monthly detailed reports with channel breakdown, creative performance, and strategic recommendations." },
    ],
  },
  {
    slug: "graphics-branding",
    title: "Graphics & Branding",
    tagline: "Visual identity that makes you unforgettable",
    description:
      "Brand identity design, UI/UX design systems, pitch decks, social media assets, and visual storytelling that elevates your brand above the noise.",
    icon: "Palette",
    what: "We create complete visual identities and design systems — from logos and brand guidelines to pitch decks and social media kits. Every asset is crafted to be consistent, memorable, and professional across all touchpoints.",
    whyUs: [
      "Full-service design: brand identity, UI/UX, print, and digital — all under one roof",
      "Design systems approach — reusable, consistent assets that scale with your brand",
      "Senior designers with agency and startup experience",
      "Fast turnaround — logo concepts in 5 days, full brand kits in 2-3 weeks",
    ],
    metrics: [
      { value: "30+", label: "Brands Designed" },
      { value: "5 days", label: "Logo Concepts" },
      { value: "100%", label: "Client Satisfaction" },
      { value: "2-3 wk", label: "Full Brand Kit" },
    ],
    how: [
      { title: "Brand Discovery", desc: "Deep-dive into your business, competitors, target audience, and brand personality through a structured workshop." },
      { title: "Visual Exploration", desc: "Moodboards, color palettes, typography selections, and 3 distinct logo concepts for your review." },
      { title: "Design Refinement", desc: "2-3 rounds of revision on the chosen direction until every detail is pixel-perfect." },
      { title: "Brand Guidelines", desc: "Comprehensive document covering logo usage, colors, typography, imagery style, and tone of voice." },
      { title: "Asset Production", desc: "Social media templates, email headers, presentation templates, business cards, and any collateral you need." },
      { title: "Design System", desc: "For digital products: a Figma component library with UI patterns, spacing system, and interaction guidelines." },
    ],
    techStack: ["Figma", "Adobe Illustrator", "Adobe Photoshop", "After Effects", "Lottie", "Framer", "Canva", "Webflow"],
    benefits: [
      "Complete brand identity package",
      "Consistent design across all touchpoints",
      "Reusable Figma design system",
      "Print and digital-ready file formats",
      "Social media template kit included",
      "Pitch deck design capability",
    ],
    caseStudy: {
      title: "FinTech Startup Brand Identity",
      challenge: "A FinTech startup needed a complete brand identity for their Series A fundraise — logo, website design, pitch deck, and social media presence.",
      result: "Delivered full brand kit in 3 weeks. The pitch deck design was cited by investors as 'the most professional we've seen from a pre-Series A company.'",
      metric: "Series A funded",
    },
    faq: [
      { q: "How many logo concepts do we get?", a: "We present 3 initial concepts based on our discovery session, then refine the chosen direction through 2-3 rounds of detailed revision." },
      { q: "Do you design pitch decks?", a: "Yes — investor pitch decks are one of our most requested services. We handle content structure, visual design, data visualization, and presentation coaching." },
      { q: "Can you create motion graphics?", a: "Yes — animated logos, product demos, social media animations, and explainer videos using After Effects and Lottie." },
    ],
  },
  {
    slug: "digital-consulting",
    title: "Digital Consulting & Strategy",
    tagline: "Strategic roadmaps for digital transformation",
    description:
      "We help organizations define and execute digital transformation strategies that align technology investments with business outcomes.",
    icon: "Lightbulb",
    what: "Digital consulting is about bridging the gap between where your business is today and where it needs to be. We assess your current technology landscape, identify inefficiencies, and build actionable roadmaps covering process optimization, platform selection, change management, and ROI-driven prioritization — so every dollar you invest in technology delivers measurable value.",
    whyUs: [
      "C-suite advisory experience across 20+ industries",
      "Vendor-agnostic recommendations — we don't resell software licenses",
      "Actionable roadmaps with timelines, budgets, and KPIs — not slide decks that gather dust",
      "Post-strategy execution support to ensure initiatives actually get delivered",
    ],
    metrics: [
      { value: "35+", label: "Strategies Delivered" },
      { value: "4.2x", label: "Avg. ROI Achieved" },
      { value: "60%", label: "Faster Time-to-Market" },
      { value: "92%", label: "Client Satisfaction" },
    ],
    how: [
      { title: "Discovery & Assessment", desc: "Stakeholder interviews, technology audit, and competitive benchmarking to understand your current state." },
      { title: "Opportunity Mapping", desc: "Identify quick wins, strategic bets, and high-impact initiatives ranked by ROI and feasibility." },
      { title: "Roadmap Development", desc: "Phased transformation roadmap with milestones, resource requirements, and success metrics." },
      { title: "Execution Support", desc: "Hands-on guidance through vendor selection, team alignment, and initiative delivery." },
    ],
    techStack: ["Miro", "Jira", "Confluence", "Power BI", "Google Analytics", "LucidChart"],
    benefits: [
      "Clear, prioritized digital transformation roadmap",
      "Vendor-agnostic technology recommendations",
      "Measurable KPIs tied to business outcomes",
      "Reduced risk of failed technology investments",
    ],
    caseStudy: {
      title: "Retail Chain Digital Transformation",
      challenge: "A 120-store retail chain was losing market share to digital-native competitors and had no cohesive technology strategy across e-commerce, inventory, and customer engagement.",
      result: "Delivered a 24-month transformation roadmap that unified their tech stack, launched e-commerce in 12 weeks, and increased online revenue by 280% in the first year.",
      metric: "280% online revenue growth",
    },
    faq: [
      { q: "How long does a digital strategy engagement take?", a: "A typical strategy engagement runs 4-8 weeks depending on organizational complexity. We deliver a comprehensive roadmap with prioritized initiatives, budgets, and timelines." },
      { q: "Do you help with execution or just strategy?", a: "Both. We can stay on as execution partners through implementation, or hand off to your internal teams with detailed specifications and change management playbooks." },
    ],
  },
  {
    slug: "digital-commerce",
    title: "Digital Commerce",
    tagline: "E-commerce platforms that drive revenue",
    description:
      "End-to-end e-commerce solutions — from storefront design and payment integration to inventory management and conversion optimization.",
    icon: "ShoppingBag",
    what: "We build and optimize digital commerce experiences that turn browsers into buyers. Whether you need a headless Shopify storefront, a custom marketplace, or a B2B ordering portal, we engineer commerce platforms with seamless checkout flows, intelligent product discovery, and integrations that keep your operations running smoothly.",
    whyUs: [
      "Full-stack commerce expertise from frontend UX to payment processing",
      "Headless architecture for blazing-fast storefronts with any backend",
      "Conversion rate optimization baked into every design decision",
      "Multi-channel selling — web, mobile, marketplaces, and social commerce",
    ],
    metrics: [
      { value: "35%", label: "Avg. Conversion Lift" },
      { value: "$10M+", label: "GMV Processed" },
      { value: "20+", label: "Stores Launched" },
      { value: "99.9%", label: "Checkout Uptime" },
    ],
    how: [
      { title: "Commerce Audit", desc: "Analyze your current store performance, conversion funnels, and competitive landscape." },
      { title: "Platform Architecture", desc: "Select and configure the right commerce stack — Shopify, WooCommerce, custom, or headless." },
      { title: "Storefront Design", desc: "Conversion-optimized product pages, cart flows, and checkout experiences." },
      { title: "Integration & Launch", desc: "Payment gateways, inventory systems, shipping providers, and analytics — all connected and tested." },
    ],
    techStack: ["Shopify", "Next.js", "Stripe", "Algolia", "Contentful", "Klaviyo"],
    benefits: [
      "Higher conversion rates through optimized UX",
      "Seamless payment and fulfillment integrations",
      "Scalable architecture for peak traffic periods",
      "Real-time inventory and order management",
    ],
    caseStudy: {
      title: "D2C Fashion Brand Replatforming",
      challenge: "A fashion brand on a legacy platform was experiencing 8-second load times and a 1.2% conversion rate, losing sales during peak campaigns.",
      result: "Migrated to a headless Shopify Plus + Next.js storefront. Load times dropped to under 1 second and conversion rate increased to 3.8% within 3 months.",
      metric: "217% conversion rate increase",
    },
    faq: [
      { q: "Which e-commerce platform do you recommend?", a: "It depends on your scale and needs. Shopify is ideal for most D2C brands, WooCommerce for content-heavy sites, and custom headless builds for high-traffic or complex B2B scenarios." },
      { q: "Can you optimize our existing store?", a: "Absolutely. We run conversion audits, speed optimization, and UX improvements on existing stores — often delivering 20-40% conversion lifts without a full rebuild." },
    ],
  },
  {
    slug: "business-applications",
    title: "Business Applications",
    tagline: "Custom apps that streamline operations",
    description:
      "Tailored business applications — ERPs, CRMs, workflow tools, and internal platforms — designed to automate processes and boost productivity.",
    icon: "LayoutDashboard",
    what: "Off-the-shelf software rarely fits complex business processes. We build custom business applications that match your exact workflows — from inventory management systems and CRM platforms to approval engines and reporting dashboards. Every application is designed for adoption, built for scale, and integrated with your existing tools.",
    whyUs: [
      "Deep business process analysis before writing any code",
      "User-centered design that drives adoption across your organization",
      "Integration-first architecture connecting all your existing systems",
      "Iterative delivery with working software every two weeks",
    ],
    metrics: [
      { value: "45+", label: "Apps Delivered" },
      { value: "90%", label: "User Adoption Rate" },
      { value: "50%", label: "Avg. Efficiency Gain" },
      { value: "99.5%", label: "Uptime SLA" },
    ],
    how: [
      { title: "Process Mapping", desc: "Document current workflows, pain points, and requirements through stakeholder workshops." },
      { title: "Solution Design", desc: "Wireframes, data models, and architecture decisions aligned with your business rules." },
      { title: "Agile Development", desc: "Two-week sprints with demos, feedback loops, and continuous refinement." },
      { title: "Deployment & Training", desc: "Staged rollout with user training, documentation, and post-launch support." },
    ],
    techStack: ["React", "Node.js", "PostgreSQL", "Power Platform", "Retool", "Prisma"],
    benefits: [
      "Applications tailored to your exact workflows",
      "Significant reduction in manual processes",
      "Seamless integration with existing tools",
      "High user adoption through intuitive design",
    ],
    caseStudy: {
      title: "Manufacturing Quality Management System",
      challenge: "A manufacturer was tracking quality inspections across 3 facilities using paper forms and disconnected spreadsheets, causing compliance risks and delayed reporting.",
      result: "Built a custom quality management platform with mobile inspection forms, real-time dashboards, and automated compliance reports — reducing inspection time by 60%.",
      metric: "60% faster inspections",
    },
    faq: [
      { q: "Can you integrate with our existing ERP or CRM?", a: "Yes. We build integration layers for SAP, Salesforce, HubSpot, NetSuite, and virtually any system with an API. Custom middleware ensures reliable, real-time data synchronization." },
      { q: "How do you ensure user adoption?", a: "We involve end users from day one through workshops and prototype testing. The result is software that matches how people actually work, not how we think they should." },
    ],
  },
  {
    slug: "data-modernization",
    title: "Data Modernization",
    tagline: "Transform legacy data into strategic assets",
    description:
      "Migrate, consolidate, and modernize your data infrastructure to unlock real-time insights and power data-driven decision-making.",
    icon: "Database",
    what: "Most organizations sit on vast amounts of data trapped in legacy systems, siloed databases, and incompatible formats. We modernize your data infrastructure — migrating to cloud-native platforms, building unified data lakes, and establishing governance frameworks that turn raw data into a competitive advantage.",
    whyUs: [
      "End-to-end data modernization from assessment to production",
      "Zero-downtime migration strategies for mission-critical systems",
      "Cloud-native architectures on AWS, Azure, or GCP",
      "Data governance and quality frameworks built in from the start",
    ],
    metrics: [
      { value: "50+", label: "Migrations Completed" },
      { value: "99.9%", label: "Data Integrity Rate" },
      { value: "70%", label: "Avg. Cost Reduction" },
      { value: "10x", label: "Query Speed Improvement" },
    ],
    how: [
      { title: "Data Assessment", desc: "Catalog existing data sources, assess quality, and map dependencies across your organization." },
      { title: "Architecture Design", desc: "Design target-state architecture — data lake, warehouse, or lakehouse — based on your analytics needs." },
      { title: "Migration Execution", desc: "Phased migration with validation, rollback plans, and zero-downtime cutover strategies." },
      { title: "Governance & Optimization", desc: "Implement data quality rules, access controls, lineage tracking, and ongoing cost optimization." },
    ],
    techStack: ["Snowflake", "AWS Redshift", "Apache Spark", "dbt", "Airflow", "Databricks"],
    benefits: [
      "Unified data platform replacing siloed systems",
      "Real-time analytics and reporting capabilities",
      "Reduced infrastructure and licensing costs",
      "Future-proof cloud-native architecture",
    ],
    caseStudy: {
      title: "Financial Services Data Lake Migration",
      challenge: "A financial services firm had data scattered across 15 legacy databases with no unified view, making regulatory reporting a 3-week manual process each quarter.",
      result: "Consolidated into a Snowflake data lake with automated ETL pipelines. Regulatory reports now generate in 2 hours instead of 3 weeks.",
      metric: "99% reporting time reduction",
    },
    faq: [
      { q: "How do you ensure data integrity during migration?", a: "We use automated validation frameworks that compare source and target data at every stage. Checksums, row counts, and business-rule validation ensure nothing is lost or corrupted." },
      { q: "Can we modernize incrementally?", a: "Absolutely. We design phased migration plans that deliver value at each stage, so you're not waiting for a big-bang cutover to see benefits." },
    ],
  },
  {
    slug: "advanced-analytics",
    title: "Advanced Analytics",
    tagline: "Turn data into actionable business intelligence",
    description:
      "Predictive analytics, machine learning models, interactive dashboards, and data science solutions that surface insights driving smarter decisions.",
    icon: "BarChart3",
    what: "We build analytics solutions that go beyond basic reporting. From predictive models that forecast demand to interactive dashboards that surface hidden patterns, we help you move from reactive decision-making to proactive, data-driven strategy. Our team combines data engineering, statistical modeling, and visualization expertise to deliver insights you can actually act on.",
    whyUs: [
      "Full-stack analytics — from data pipeline to executive dashboard",
      "Predictive and prescriptive models, not just descriptive reporting",
      "Domain expertise across retail, finance, healthcare, and logistics",
      "Self-service analytics tools that empower your team",
    ],
    metrics: [
      { value: "25%", label: "Avg. Revenue Lift" },
      { value: "40+", label: "Dashboards Built" },
      { value: "92%", label: "Forecast Accuracy" },
      { value: "3x", label: "Faster Decision-Making" },
    ],
    how: [
      { title: "Data Discovery", desc: "Identify key data sources, define KPIs, and establish the questions your analytics need to answer." },
      { title: "Pipeline Development", desc: "Build automated ETL/ELT pipelines to clean, transform, and load data into your analytics platform." },
      { title: "Model Building", desc: "Develop predictive models, segmentation algorithms, or anomaly detection tailored to your use cases." },
      { title: "Visualization & Delivery", desc: "Interactive dashboards, automated reports, and alert systems that put insights in the right hands." },
    ],
    techStack: ["Python", "Tableau", "Power BI", "dbt", "Scikit-learn", "Apache Spark"],
    benefits: [
      "Predictive insights that drive proactive decisions",
      "Self-service dashboards for non-technical users",
      "Automated reporting replacing manual spreadsheets",
      "Measurable ROI tied to business outcomes",
    ],
    caseStudy: {
      title: "Retail Demand Forecasting Platform",
      challenge: "A grocery chain was experiencing 15% inventory waste due to inaccurate demand forecasting across 80 stores and 5,000+ SKUs.",
      result: "Built a machine learning forecasting platform that reduced waste by 35% and improved stock availability by 20%, saving $2.4M annually.",
      metric: "$2.4M annual savings",
    },
    faq: [
      { q: "Do we need a data warehouse first?", a: "Not necessarily. We can work with your existing data sources and build lightweight pipelines. However, for mature analytics, we often recommend establishing a proper data warehouse as a foundation." },
      { q: "Can non-technical users operate the dashboards?", a: "Absolutely. We design self-service interfaces with filters, drill-downs, and natural language queries so business users can explore data without SQL knowledge." },
    ],
  },
  {
    slug: "connected-intelligence",
    title: "Connected Intelligence",
    tagline: "IoT and AI converging for smarter operations",
    description:
      "Connect devices, sensors, and systems with intelligent analytics to enable real-time monitoring, predictive maintenance, and operational optimization.",
    icon: "Network",
    what: "Connected intelligence brings together IoT infrastructure, edge computing, and AI to create systems that sense, analyze, and act autonomously. We design end-to-end solutions — from sensor deployment and data ingestion to machine learning models that predict failures, optimize energy usage, and automate operational decisions in real time.",
    whyUs: [
      "End-to-end IoT and AI expertise under one roof",
      "Edge computing capabilities for low-latency, real-time processing",
      "Proven deployments in manufacturing, logistics, and smart facilities",
      "Scalable architectures handling millions of data points per day",
    ],
    metrics: [
      { value: "1M+", label: "Data Points/Day" },
      { value: "45%", label: "Downtime Reduction" },
      { value: "30%", label: "Energy Savings" },
      { value: "15+", label: "Deployments Live" },
    ],
    how: [
      { title: "Infrastructure Assessment", desc: "Audit existing equipment, connectivity, and data systems to design the optimal IoT architecture." },
      { title: "Sensor & Edge Setup", desc: "Deploy sensors, gateways, and edge computing nodes with secure, reliable data transmission." },
      { title: "Data Pipeline & Analytics", desc: "Build real-time ingestion pipelines and ML models for monitoring, prediction, and anomaly detection." },
      { title: "Dashboard & Automation", desc: "Deliver operator dashboards with alerts, and automated response systems for critical events." },
    ],
    techStack: ["AWS IoT Core", "Azure IoT Hub", "MQTT", "Apache Kafka", "TensorFlow Lite", "Grafana"],
    benefits: [
      "Real-time visibility into operations and assets",
      "Predictive maintenance reducing unplanned downtime",
      "Energy and resource optimization",
      "Scalable from pilot to enterprise-wide deployment",
    ],
    caseStudy: {
      title: "Smart Factory Predictive Maintenance",
      challenge: "A manufacturing plant experienced $1.8M in annual losses from unplanned equipment downtime across 200+ machines with no predictive capability.",
      result: "Deployed IoT sensors and ML-based failure prediction models that reduced unplanned downtime by 45% and saved $810K in the first year.",
      metric: "45% downtime reduction",
    },
    faq: [
      { q: "What kind of sensors and devices do you support?", a: "We're hardware-agnostic and work with industrial PLCs, environmental sensors, RFID, GPS trackers, and consumer IoT devices. We help select the right hardware for your use case." },
      { q: "How do you handle connectivity in remote locations?", a: "We design for unreliable connectivity using edge computing, local data buffering, and store-and-forward protocols so no data is lost even when network is intermittent." },
    ],
  },
  {
    slug: "data-management",
    title: "Data Management",
    tagline: "Govern, protect, and maximize your data",
    description:
      "Comprehensive data governance, quality management, master data management, and compliance frameworks that ensure your data is accurate, secure, and accessible.",
    icon: "HardDrive",
    what: "Data management is the foundation of every successful data initiative. We implement governance frameworks, data quality rules, master data management, cataloging, and compliance controls that ensure your data is trustworthy, discoverable, and properly governed — enabling confident decision-making and regulatory compliance.",
    whyUs: [
      "Framework-driven approach aligned with DAMA-DMBOK best practices",
      "Compliance expertise across GDPR, CCPA, HIPAA, and SOX",
      "Automated data quality monitoring — not just one-time cleanup",
      "Business-friendly data catalogs that make data discoverable by everyone",
    ],
    metrics: [
      { value: "99.5%", label: "Data Quality Score" },
      { value: "100%", label: "Compliance Rate" },
      { value: "60%", label: "Faster Data Access" },
      { value: "30+", label: "Frameworks Deployed" },
    ],
    how: [
      { title: "Data Maturity Assessment", desc: "Evaluate your current data management practices against industry frameworks and identify gaps." },
      { title: "Governance Framework", desc: "Define data ownership, stewardship roles, policies, and standards across the organization." },
      { title: "Quality & MDM Implementation", desc: "Deploy data quality rules, deduplication, master data management, and automated monitoring." },
      { title: "Catalog & Compliance", desc: "Launch a searchable data catalog and implement privacy controls for regulatory compliance." },
    ],
    techStack: ["Collibra", "Informatica", "Apache Atlas", "Great Expectations", "Alation", "Talend"],
    benefits: [
      "Trusted, high-quality data across the organization",
      "Full regulatory compliance with audit trails",
      "Self-service data discovery for business users",
      "Reduced risk of data breaches and errors",
    ],
    caseStudy: {
      title: "Healthcare Data Governance Program",
      challenge: "A hospital network with 12 facilities had inconsistent patient data across systems, creating compliance risks and impacting care quality.",
      result: "Implemented a master data management platform and governance framework that unified patient records, achieving 99.7% data accuracy and full HIPAA compliance.",
      metric: "99.7% data accuracy",
    },
    faq: [
      { q: "How long does a data governance program take to implement?", a: "A foundational governance framework takes 8-12 weeks. Full enterprise rollout with MDM and cataloging typically spans 4-6 months, delivered in phases with value at each stage." },
      { q: "Do we need to buy expensive tools?", a: "Not necessarily. We evaluate your needs and recommend the right mix — from open-source tools like Apache Atlas to enterprise platforms like Collibra, depending on your scale and budget." },
    ],
  },
  {
    slug: "generative-ai",
    title: "Generative AI",
    tagline: "Create, personalize, and scale with AI",
    description:
      "Harness generative AI for content creation, code generation, personalized experiences, and intelligent assistants that transform how your business operates.",
    icon: "Sparkles",
    what: "Generative AI is reshaping every industry. We help you move beyond experimentation to production-grade generative AI solutions — custom chatbots, content generation pipelines, AI copilots for your team, document processing, and personalization engines. We focus on responsible AI with guardrails, evaluation, and human oversight built into every system.",
    whyUs: [
      "Production-grade generative AI — not just wrappers around ChatGPT",
      "Custom guardrails, content filtering, and safety systems",
      "Cost-optimized architectures with intelligent model routing",
      "Responsible AI practices with bias testing and transparency",
    ],
    metrics: [
      { value: "20+", label: "GenAI Projects" },
      { value: "75%", label: "Avg. Productivity Gain" },
      { value: "10x", label: "Content Speed" },
      { value: "<1s", label: "Avg. Latency" },
    ],
    how: [
      { title: "Use Case Definition", desc: "Identify high-impact generative AI opportunities and define success criteria with measurable KPIs." },
      { title: "Architecture & Safety", desc: "Design the AI pipeline with model selection, guardrails, content filtering, and fallback strategies." },
      { title: "Development & Fine-Tuning", desc: "Build, prompt-engineer, and optionally fine-tune models on your domain data for superior results." },
      { title: "Deployment & Monitoring", desc: "Production deployment with evaluation frameworks, cost monitoring, and continuous improvement loops." },
    ],
    techStack: ["OpenAI GPT-4o", "Claude", "Stable Diffusion", "LangChain", "Pinecone", "Guardrails AI"],
    benefits: [
      "Massive productivity gains across content workflows",
      "Personalized customer experiences at scale",
      "Built-in safety guardrails and content filtering",
      "Cost-efficient model routing and caching",
    ],
    caseStudy: {
      title: "Enterprise Knowledge Assistant",
      challenge: "A consulting firm with 10,000+ internal documents needed a way for consultants to instantly find relevant insights, templates, and past work.",
      result: "Built a RAG-powered AI assistant that searches across all internal knowledge bases, generating accurate answers with source citations — saving 8 hours per consultant per week.",
      metric: "8 hrs/week saved per user",
    },
    faq: [
      { q: "How do you prevent AI hallucinations?", a: "We use retrieval-augmented generation (RAG) grounded in your actual data, combined with citation requirements, confidence scoring, and human-in-the-loop review for critical outputs." },
      { q: "Can we use generative AI with our proprietary data securely?", a: "Yes. We deploy on private cloud instances, use enterprise API agreements with data isolation, and can run open-source models on your own infrastructure for maximum data security." },
    ],
  },
  {
    slug: "cloud-operations",
    title: "Cloud Operations & Migration",
    tagline: "Seamless cloud migration and optimization",
    description:
      "End-to-end cloud migration, infrastructure optimization, and ongoing operations management across AWS, Azure, and Google Cloud.",
    icon: "CloudCog",
    what: "We migrate your workloads to the cloud and keep them running at peak efficiency. From lift-and-shift migrations to cloud-native re-architecture, we handle the entire journey — assessment, migration planning, execution, and ongoing cost and performance optimization. Our team manages multi-cloud and hybrid environments with 24/7 monitoring and support.",
    whyUs: [
      "Certified architects across AWS, Azure, and GCP",
      "Zero-downtime migration methodology with automated rollback",
      "FinOps expertise — we typically reduce cloud bills by 30-40%",
      "24/7 monitoring and incident response for production workloads",
    ],
    metrics: [
      { value: "100+", label: "Migrations Completed" },
      { value: "35%", label: "Avg. Cost Savings" },
      { value: "99.99%", label: "Uptime Achieved" },
      { value: "0", label: "Data Loss Incidents" },
    ],
    how: [
      { title: "Cloud Assessment", desc: "Inventory your current infrastructure, assess cloud readiness, and build a TCO comparison model." },
      { title: "Migration Planning", desc: "Design the migration strategy — rehost, replatform, or refactor — with a phased execution plan." },
      { title: "Migration Execution", desc: "Automated migration with continuous validation, testing, and zero-downtime cutover." },
      { title: "Optimization & Ops", desc: "Right-sizing, reserved instances, auto-scaling, and ongoing monitoring for cost and performance." },
    ],
    techStack: ["AWS", "Azure", "Google Cloud", "Terraform", "CloudFormation", "Datadog"],
    benefits: [
      "Reduced infrastructure costs with cloud economics",
      "Improved scalability and global availability",
      "Zero-downtime migration execution",
      "Ongoing optimization and FinOps management",
    ],
    caseStudy: {
      title: "Enterprise Data Center to AWS Migration",
      challenge: "A media company needed to migrate 200+ servers from an aging data center to AWS before a lease expiration deadline, without disrupting live streaming services.",
      result: "Completed full migration in 10 weeks with zero downtime, achieving 35% infrastructure cost reduction and 3x improvement in content delivery speed.",
      metric: "35% cost reduction",
    },
    faq: [
      { q: "How long does a cloud migration take?", a: "It depends on complexity. A small environment (10-20 servers) takes 4-6 weeks. Enterprise migrations with hundreds of servers typically run 3-6 months in phases." },
      { q: "Can you manage multi-cloud environments?", a: "Yes. We design and manage hybrid and multi-cloud architectures across AWS, Azure, and GCP using infrastructure as code and unified monitoring." },
    ],
  },
  {
    slug: "cloud-app-development",
    title: "Cloud App Development & Integration",
    tagline: "Cloud-native apps built for scale",
    description:
      "Design and build cloud-native applications with microservices, serverless functions, and seamless API integrations across your technology ecosystem.",
    icon: "Cloud",
    what: "We build applications designed for the cloud from the ground up — leveraging containers, serverless computing, managed databases, and event-driven architectures to deliver applications that scale automatically, cost less to run, and deploy continuously. Our integration expertise connects your cloud apps to any SaaS platform, legacy system, or third-party API.",
    whyUs: [
      "Cloud-native architecture with containers, serverless, and managed services",
      "CI/CD pipelines delivering multiple deployments per day",
      "API-first design enabling seamless ecosystem integration",
      "Auto-scaling infrastructure that handles traffic spikes without manual intervention",
    ],
    metrics: [
      { value: "30+", label: "Cloud Apps Built" },
      { value: "50+", label: "API Integrations" },
      { value: "99.9%", label: "Availability" },
      { value: "10x", label: "Deployment Frequency" },
    ],
    how: [
      { title: "Architecture Design", desc: "Define microservices boundaries, data stores, communication patterns, and cloud service selection." },
      { title: "API & Integration Layer", desc: "Build RESTful or event-driven APIs with connectors to SaaS platforms and legacy systems." },
      { title: "Cloud-Native Development", desc: "Containerized services with CI/CD, infrastructure as code, and automated testing." },
      { title: "Observability & Operations", desc: "Distributed tracing, centralized logging, alerting, and auto-scaling for production readiness." },
    ],
    techStack: ["AWS Lambda", "Docker", "Kubernetes", "API Gateway", "EventBridge", "Terraform"],
    benefits: [
      "Auto-scaling applications that handle any load",
      "Rapid deployment with CI/CD pipelines",
      "Seamless integration with your entire ecosystem",
      "Pay-per-use economics reducing operational costs",
    ],
    caseStudy: {
      title: "Insurance Claims Processing Platform",
      challenge: "An insurance company needed to replace a monolithic claims system that took 48 hours to process a claim and couldn't integrate with new digital channels.",
      result: "Built a cloud-native microservices platform on AWS that reduced claims processing to 4 hours, integrated with 8 partner APIs, and scaled to handle 10x volume during natural disasters.",
      metric: "92% faster processing",
    },
    faq: [
      { q: "Should we go serverless or containers?", a: "It depends on your workload. Serverless is ideal for event-driven, variable-traffic workloads. Containers suit long-running processes or teams needing more control. We often use both in the same architecture." },
      { q: "How do you handle integration with legacy systems?", a: "We build adapter layers and API gateways that wrap legacy systems, allowing cloud apps to communicate without modifying the legacy codebase. This enables incremental modernization." },
    ],
  },
  {
    slug: "managed-services",
    title: "Managed Services",
    tagline: "We run your IT so you don't have to",
    description:
      "Comprehensive IT managed services — infrastructure monitoring, helpdesk support, patch management, and proactive maintenance — so you can focus on your business.",
    icon: "Settings",
    what: "Our managed services take the burden of IT operations off your shoulders. We provide 24/7 monitoring, proactive maintenance, helpdesk support, security patching, and performance optimization for your entire technology stack. You get a dedicated team that knows your systems inside out, with clear SLAs and predictable monthly costs.",
    whyUs: [
      "24/7 NOC with 15-minute response times for critical issues",
      "Predictable monthly pricing — no surprise bills",
      "Proactive monitoring that catches issues before users do",
      "Dedicated account manager who knows your business",
    ],
    metrics: [
      { value: "24/7", label: "Support Coverage" },
      { value: "15 min", label: "Critical Response" },
      { value: "99.9%", label: "SLA Compliance" },
      { value: "40%", label: "IT Cost Savings" },
    ],
    how: [
      { title: "Environment Onboarding", desc: "Document your infrastructure, applications, and support processes during a structured transition." },
      { title: "Monitoring Setup", desc: "Deploy monitoring agents, configure alerts, and establish escalation procedures." },
      { title: "Ongoing Operations", desc: "24/7 monitoring, incident management, patch management, and performance optimization." },
      { title: "Continuous Improvement", desc: "Monthly service reviews, capacity planning, and technology upgrade recommendations." },
    ],
    techStack: ["Datadog", "PagerDuty", "ServiceNow", "Ansible", "Terraform", "Grafana"],
    benefits: [
      "Predictable IT costs with fixed monthly pricing",
      "Reduced downtime through proactive monitoring",
      "Expert team without the overhead of hiring",
      "Focus on your core business, not IT firefighting",
    ],
    caseStudy: {
      title: "Mid-Market Company IT Outsourcing",
      challenge: "A 500-person company was spending $1.2M annually on a 6-person IT team that was constantly firefighting instead of driving innovation.",
      result: "Transitioned to our managed services model, reducing IT costs by 40% while improving uptime from 97% to 99.9% and freeing internal staff for strategic projects.",
      metric: "40% IT cost reduction",
    },
    faq: [
      { q: "What's included in your managed services?", a: "24/7 monitoring and alerting, helpdesk support (L1-L3), patch management, backup management, security monitoring, monthly reporting, and a dedicated account manager." },
      { q: "How do you handle the transition from our current team?", a: "We run a structured 4-6 week transition with knowledge transfer sessions, documentation, and a parallel support period to ensure zero disruption to your operations." },
    ],
  },
  {
    slug: "contact-center",
    title: "Contact Center",
    tagline: "Elevate every customer interaction",
    description:
      "Modern contact center solutions — omnichannel support, AI-powered routing, workforce management, and analytics that transform customer experience.",
    icon: "Headphones",
    what: "We design and implement contact center solutions that deliver exceptional customer experiences across every channel — voice, email, chat, social media, and messaging. From cloud-based CCaaS platforms to AI-powered chatbots and intelligent routing, we help you reduce wait times, improve first-contact resolution, and scale support without proportionally scaling headcount.",
    whyUs: [
      "Omnichannel expertise across voice, chat, email, social, and messaging",
      "AI-powered routing and chatbots that deflect 40%+ of routine inquiries",
      "Workforce management optimization for staffing and scheduling",
      "Real-time analytics dashboards for supervisors and executives",
    ],
    metrics: [
      { value: "40%", label: "Call Deflection Rate" },
      { value: "85%", label: "First Contact Resolution" },
      { value: "30s", label: "Avg. Wait Time" },
      { value: "95%", label: "CSAT Score" },
    ],
    how: [
      { title: "Needs Assessment", desc: "Analyze current contact volumes, channels, pain points, and customer journey touchpoints." },
      { title: "Platform Design", desc: "Select and configure the CCaaS platform with routing rules, IVR flows, and channel integrations." },
      { title: "AI & Automation", desc: "Deploy chatbots, auto-responses, and intelligent routing to handle routine inquiries automatically." },
      { title: "Launch & Optimize", desc: "Go live with agent training, real-time monitoring dashboards, and continuous optimization." },
    ],
    techStack: ["Amazon Connect", "Twilio Flex", "Genesys Cloud", "Dialogflow", "Salesforce Service Cloud", "Five9"],
    benefits: [
      "Reduced wait times and improved CSAT scores",
      "AI chatbots handling routine inquiries 24/7",
      "Unified agent desktop across all channels",
      "Real-time analytics for data-driven decisions",
    ],
    caseStudy: {
      title: "Insurance Company Contact Center Modernization",
      challenge: "An insurance company's legacy call center had 8-minute average wait times, no digital channels, and agent turnover exceeding 40% annually.",
      result: "Implemented a cloud-based omnichannel contact center with AI chatbot handling 45% of inquiries. Wait times dropped to 25 seconds and agent satisfaction improved by 60%.",
      metric: "45% automated deflection",
    },
    faq: [
      { q: "Can you integrate with our existing CRM?", a: "Yes. We integrate with Salesforce, HubSpot, Zendesk, and custom CRMs to give agents a unified view of customer history and context during every interaction." },
      { q: "How quickly can we go live?", a: "A basic cloud contact center can go live in 4-6 weeks. Complex omnichannel implementations with AI and custom integrations typically take 8-12 weeks." },
    ],
  },
  {
    slug: "finance-accounting",
    title: "Finance & Accounting",
    tagline: "Streamline financial operations with precision",
    description:
      "Outsourced finance and accounting services — bookkeeping, financial reporting, accounts payable/receivable, and CFO advisory — with accuracy and compliance.",
    icon: "Calculator",
    what: "We provide comprehensive finance and accounting services that scale with your business. From daily bookkeeping and payroll processing to monthly financial reporting and strategic CFO advisory, our team ensures your finances are accurate, compliant, and transparent. We leverage modern accounting platforms and automation to deliver faster close cycles and real-time financial visibility.",
    whyUs: [
      "CPA-led team with expertise across multiple industries and jurisdictions",
      "Cloud-based accounting platforms for real-time financial visibility",
      "Automated workflows reducing manual effort by 70%+",
      "Scalable from startup bookkeeping to enterprise financial operations",
    ],
    metrics: [
      { value: "99.8%", label: "Accuracy Rate" },
      { value: "70%", label: "Process Automation" },
      { value: "5-day", label: "Month-End Close" },
      { value: "50+", label: "Clients Served" },
    ],
    how: [
      { title: "Financial Assessment", desc: "Review current processes, chart of accounts, and reporting requirements to design the optimal service model." },
      { title: "System Setup", desc: "Configure cloud accounting platforms, automate recurring transactions, and set up reporting templates." },
      { title: "Transition & Operations", desc: "Structured handover with parallel processing period to ensure continuity and accuracy." },
      { title: "Ongoing Management", desc: "Daily transaction processing, monthly reconciliations, financial reporting, and advisory support." },
    ],
    techStack: ["QuickBooks Online", "Xero", "NetSuite", "Dext", "Fathom", "Stripe"],
    benefits: [
      "Accurate, timely financial reporting every month",
      "Reduced overhead vs. in-house finance team",
      "Real-time financial dashboards and KPIs",
      "Compliance with local and international standards",
    ],
    caseStudy: {
      title: "Tech Startup Financial Operations",
      challenge: "A fast-growing SaaS startup had outgrown its bookkeeper and needed investor-grade financial reporting, multi-currency support, and revenue recognition compliance.",
      result: "Implemented a full outsourced finance function with automated revenue recognition, 5-day month-end close, and investor-ready financial packages that supported their Series B raise.",
      metric: "5-day month-end close",
    },
    faq: [
      { q: "How do you handle data security for financial information?", a: "We use encrypted cloud platforms, role-based access controls, and strict data handling policies. All team members are background-checked and bound by confidentiality agreements." },
      { q: "Can you handle multi-currency and international operations?", a: "Yes. We manage multi-currency accounting, international tax compliance, transfer pricing, and consolidated reporting for companies operating across multiple jurisdictions." },
    ],
  },
  {
    slug: "staff-augmentation",
    title: "Staff Augmentation",
    tagline: "Top talent embedded in your team",
    description:
      "Scale your engineering, design, and operations teams with pre-vetted professionals who integrate seamlessly into your workflows and culture.",
    icon: "Users",
    what: "When you need to scale your team quickly without the overhead of full-time hiring, our staff augmentation service provides pre-vetted engineers, designers, data scientists, and project managers who embed directly into your team. They use your tools, attend your standups, and operate as full team members — with the flexibility to scale up or down as projects evolve.",
    whyUs: [
      "Pre-vetted talent pool with rigorous technical assessments",
      "48-hour candidate shortlist from request to profiles",
      "Full cultural and process alignment — not just skill matching",
      "Flexible engagement models — monthly, quarterly, or project-based",
    ],
    metrics: [
      { value: "48 hrs", label: "Time to Shortlist" },
      { value: "200+", label: "Active Professionals" },
      { value: "95%", label: "Client Retention" },
      { value: "4.8/5", label: "Avg. Rating" },
    ],
    how: [
      { title: "Requirements Gathering", desc: "Define role specifications, technical skills, experience level, and team culture fit criteria." },
      { title: "Candidate Matching", desc: "Present 2-3 pre-vetted candidates within 48 hours with detailed profiles and assessment results." },
      { title: "Onboarding", desc: "Structured onboarding process with your team's tools, codebase, and development workflows." },
      { title: "Ongoing Management", desc: "Regular performance reviews, feedback loops, and seamless scaling as your needs evolve." },
    ],
    techStack: ["Jira", "Slack", "GitHub", "Confluence", "Linear", "Notion"],
    benefits: [
      "Rapid team scaling without hiring overhead",
      "Pre-vetted talent ready to contribute from day one",
      "Flexible contracts that adapt to your project needs",
      "Zero recruitment costs and reduced time-to-productivity",
    ],
    caseStudy: {
      title: "FinTech Engineering Team Scale-Up",
      challenge: "A FinTech company won a major contract and needed to double their engineering team from 8 to 16 developers within 4 weeks to meet delivery timelines.",
      result: "Provided 8 senior engineers who onboarded in 1 week and contributed production code within 2 weeks. The project was delivered on time and under budget.",
      metric: "100% on-time delivery",
    },
    faq: [
      { q: "How quickly can you provide candidates?", a: "We present 2-3 pre-vetted candidate profiles within 48 hours. After your interviews, onboarding can begin within 1 week." },
      { q: "What happens if a team member isn't a good fit?", a: "We offer a 2-week satisfaction guarantee. If any team member isn't meeting expectations, we provide a replacement at no additional cost." },
    ],
  },
  {
    slug: "legal-process-outsourcing",
    title: "Legal Process Outsourcing",
    tagline: "Efficient legal support at scale",
    description:
      "Outsourced legal operations — contract management, document review, compliance support, and legal research — delivered by trained legal professionals.",
    icon: "Scale",
    what: "Our legal process outsourcing services reduce the cost and complexity of legal operations. We provide trained legal professionals who handle contract lifecycle management, due diligence document review, regulatory compliance monitoring, legal research, and litigation support — allowing your legal team to focus on strategic matters while we manage the high-volume operational work.",
    whyUs: [
      "Law-trained professionals with industry-specific expertise",
      "AI-assisted document review for speed and accuracy",
      "Strict confidentiality protocols and data security measures",
      "Scalable teams that flex with your caseload demands",
    ],
    metrics: [
      { value: "60%", label: "Cost Savings" },
      { value: "99.2%", label: "Review Accuracy" },
      { value: "3x", label: "Faster Turnaround" },
      { value: "500K+", label: "Documents Processed" },
    ],
    how: [
      { title: "Scope Definition", desc: "Identify the legal processes to outsource, define quality standards, and establish communication protocols." },
      { title: "Team Assembly", desc: "Assemble a dedicated team of legal professionals with relevant jurisdiction and domain expertise." },
      { title: "Process Setup", desc: "Configure workflows, review protocols, and AI-assisted tools for efficient document processing." },
      { title: "Delivery & QA", desc: "Ongoing delivery with multi-tier quality assurance, regular reporting, and continuous process improvement." },
    ],
    techStack: ["Relativity", "Kira Systems", "ContractPodAi", "iManage", "Luminance", "DocuSign"],
    benefits: [
      "Significant cost reduction vs. in-house legal staff",
      "Faster turnaround on document review and research",
      "AI-enhanced accuracy for contract analysis",
      "Scalable capacity for peak workload periods",
    ],
    caseStudy: {
      title: "Corporate M&A Due Diligence",
      challenge: "A law firm managing a major acquisition needed to review 50,000+ documents within a 6-week deadline with limited internal capacity.",
      result: "Deployed a 15-person LPO team with AI-assisted review tools. Completed the review in 4 weeks with 99.4% accuracy, saving the firm $400K compared to associate-level billing.",
      metric: "$400K cost savings",
    },
    faq: [
      { q: "How do you ensure confidentiality?", a: "All team members sign NDAs, work in secure environments with monitored access, and we comply with international data protection regulations. We're SOC 2 compliant." },
      { q: "Can you handle jurisdiction-specific legal work?", a: "Yes. We have professionals experienced in US, UK, EU, and Asian jurisdictions. We match team expertise to your specific jurisdictional requirements." },
    ],
  },
  {
    slug: "recruitment-outsourcing",
    title: "Recruitment Process Outsourcing",
    tagline: "Hire better, faster, and cheaper",
    description:
      "End-to-end recruitment outsourcing — sourcing, screening, interviewing, and onboarding — that reduces time-to-hire and improves candidate quality.",
    icon: "UserPlus",
    what: "Our recruitment process outsourcing (RPO) service takes over all or part of your hiring process. We act as an extension of your HR team — sourcing candidates, managing job postings, screening resumes, conducting initial interviews, and coordinating the entire hiring pipeline. Our data-driven approach and dedicated recruiters consistently deliver better candidates faster and at lower cost than traditional recruitment.",
    whyUs: [
      "Dedicated recruitment team that learns your culture and standards",
      "AI-powered sourcing reaching passive candidates competitors miss",
      "Structured interview frameworks reducing bias and improving quality",
      "Full analytics dashboard tracking pipeline, time-to-hire, and cost-per-hire",
    ],
    metrics: [
      { value: "50%", label: "Faster Time-to-Hire" },
      { value: "40%", label: "Cost Reduction" },
      { value: "92%", label: "Retention at 12 Months" },
      { value: "1000+", label: "Placements Made" },
    ],
    how: [
      { title: "Alignment", desc: "Understand your hiring needs, culture, compensation benchmarks, and employer brand positioning." },
      { title: "Sourcing & Screening", desc: "Multi-channel sourcing, resume screening, and initial assessments to build a qualified shortlist." },
      { title: "Interview Management", desc: "Coordinate interviews, provide structured assessment frameworks, and manage candidate communication." },
      { title: "Offer & Onboarding", desc: "Support offer negotiation, background checks, and structured onboarding for successful starts." },
    ],
    techStack: ["LinkedIn Recruiter", "Greenhouse", "Lever", "HireVue", "Workday", "BambooHR"],
    benefits: [
      "Faster hiring without sacrificing quality",
      "Reduced recruitment costs vs. agencies",
      "Consistent candidate experience and employer brand",
      "Data-driven hiring decisions with full analytics",
    ],
    caseStudy: {
      title: "Tech Company Rapid Scaling",
      challenge: "A Series B startup needed to hire 45 engineers across 4 specializations within 6 months while maintaining their high hiring bar.",
      result: "Deployed a dedicated 4-person RPO team that filled all 45 positions in 5 months with a 94% 12-month retention rate — 40% cheaper than their previous agency model.",
      metric: "45 hires in 5 months",
    },
    faq: [
      { q: "How is RPO different from a staffing agency?", a: "Unlike agencies that work on a per-role fee basis, RPO is an ongoing partnership where a dedicated team manages your entire recruitment process with monthly pricing, deeper cultural integration, and continuous improvement." },
      { q: "Can you handle niche technical hiring?", a: "Yes. We have specialized sourcers for engineering, data science, product, and design roles. Our technical assessment frameworks are calibrated per discipline." },
    ],
  },
  {
    slug: "digital-infrastructure",
    title: "Digital Infrastructure Services",
    tagline: "Resilient infrastructure powering your business",
    description:
      "Design, deploy, and manage enterprise IT infrastructure — networking, storage, compute, and disaster recovery — for on-premise, cloud, and hybrid environments.",
    icon: "Server",
    what: "We design and manage the foundational IT infrastructure your business depends on. From network architecture and server management to storage solutions and disaster recovery, we ensure your infrastructure is reliable, secure, and optimized for performance. Whether you're running on-premise, in the cloud, or a hybrid of both, we architect solutions that meet your availability, compliance, and budget requirements.",
    whyUs: [
      "Certified engineers across networking, storage, compute, and virtualization",
      "24/7 infrastructure monitoring with 15-minute critical response SLA",
      "Disaster recovery and business continuity planning built into every design",
      "Hybrid infrastructure expertise bridging on-premise and cloud environments",
    ],
    metrics: [
      { value: "99.99%", label: "Infrastructure Uptime" },
      { value: "15 min", label: "Incident Response" },
      { value: "500+", label: "Servers Managed" },
      { value: "RPO <1hr", label: "Disaster Recovery" },
    ],
    how: [
      { title: "Infrastructure Assessment", desc: "Audit current systems, identify risks and bottlenecks, and document the existing environment." },
      { title: "Architecture Design", desc: "Design target infrastructure with high availability, disaster recovery, and security controls." },
      { title: "Implementation", desc: "Deploy and configure infrastructure with minimal disruption, thorough testing, and documentation." },
      { title: "Managed Operations", desc: "24/7 monitoring, proactive maintenance, capacity planning, and incident management." },
    ],
    techStack: ["VMware", "Cisco", "Dell EMC", "Veeam", "Fortinet", "Nutanix"],
    benefits: [
      "Enterprise-grade reliability and uptime",
      "Proactive monitoring preventing issues before they impact users",
      "Disaster recovery ensuring business continuity",
      "Optimized infrastructure costs and resource utilization",
    ],
    caseStudy: {
      title: "Hospital Network Infrastructure Overhaul",
      challenge: "A hospital network with 8 locations had aging infrastructure causing weekly outages that impacted patient care systems and regulatory compliance.",
      result: "Redesigned the entire infrastructure with redundant networking, virtualized servers, and automated failover. Achieved 99.99% uptime and full compliance with healthcare regulations.",
      metric: "99.99% uptime achieved",
    },
    faq: [
      { q: "Do you support on-premise infrastructure?", a: "Yes. We manage on-premise servers, networking, and storage alongside cloud environments. Many of our clients run hybrid architectures where we manage both." },
      { q: "What's your disaster recovery capability?", a: "We design DR solutions with RPO (recovery point) under 1 hour and RTO (recovery time) under 4 hours for critical systems, using automated failover and regular DR testing." },
    ],
  },
  {
    slug: "security",
    title: "Security",
    tagline: "Protect your assets against every threat",
    description:
      "Comprehensive cybersecurity services — vulnerability assessments, penetration testing, security operations, compliance, and incident response.",
    icon: "ShieldCheck",
    what: "Cybersecurity is not optional — it's a business imperative. We provide end-to-end security services including vulnerability assessments, penetration testing, security architecture reviews, SOC operations, compliance management, and incident response. Our approach combines proactive threat hunting with robust defense-in-depth strategies to protect your data, applications, and infrastructure from evolving threats.",
    whyUs: [
      "Certified security professionals (CISSP, CEH, OSCP) with real-world experience",
      "24/7 security operations center (SOC) with threat intelligence",
      "Compliance expertise across SOC 2, ISO 27001, HIPAA, PCI-DSS, and GDPR",
      "Proactive threat hunting — we find vulnerabilities before attackers do",
    ],
    metrics: [
      { value: "24/7", label: "SOC Monitoring" },
      { value: "99.9%", label: "Threat Detection Rate" },
      { value: "< 30 min", label: "Incident Response" },
      { value: "200+", label: "Pen Tests Completed" },
    ],
    how: [
      { title: "Security Assessment", desc: "Comprehensive vulnerability scanning, penetration testing, and security architecture review." },
      { title: "Remediation Planning", desc: "Prioritized remediation roadmap with risk scoring and step-by-step fix guidance." },
      { title: "Security Implementation", desc: "Deploy security controls, SIEM configuration, endpoint protection, and access management." },
      { title: "Ongoing Monitoring", desc: "24/7 SOC monitoring, threat hunting, incident response, and regular security reviews." },
    ],
    techStack: ["CrowdStrike", "Splunk", "Palo Alto Networks", "Tenable", "Okta", "HashiCorp Vault"],
    benefits: [
      "Proactive threat detection and prevention",
      "Regulatory compliance across major frameworks",
      "Reduced risk of data breaches and downtime",
      "Expert incident response when threats emerge",
    ],
    caseStudy: {
      title: "E-Commerce Security Overhaul",
      challenge: "An e-commerce platform handling 100K+ transactions monthly had failed a PCI-DSS audit and discovered critical vulnerabilities in their payment processing pipeline.",
      result: "Conducted a full security overhaul — patched 47 vulnerabilities, implemented WAF and SIEM, achieved PCI-DSS compliance, and established 24/7 monitoring. Zero security incidents in 18 months since.",
      metric: "0 incidents in 18 months",
    },
    faq: [
      { q: "How often should we do penetration testing?", a: "We recommend quarterly pen tests for high-risk environments and at minimum annually. Additionally, any major application change or infrastructure modification should trigger a targeted assessment." },
      { q: "Can you help us achieve SOC 2 compliance?", a: "Yes. We provide end-to-end SOC 2 readiness — gap assessment, policy development, control implementation, evidence collection, and auditor liaison through successful certification." },
    ],
  },
  {
    slug: "emerging-technologies",
    title: "Emerging Technologies",
    tagline: "Future-proof with cutting-edge innovation",
    description:
      "Explore and adopt emerging technologies — blockchain, AR/VR, quantum computing readiness, Web3, and edge computing — with strategic guidance and proof-of-concept development.",
    icon: "Cpu",
    what: "Staying ahead means experimenting with tomorrow's technology today. We help organizations evaluate, pilot, and adopt emerging technologies that offer genuine competitive advantages. From blockchain-based supply chain transparency to AR-powered training experiences, we cut through the hype to identify which technologies will actually move the needle for your business — then build production-ready proofs of concept.",
    whyUs: [
      "Research-driven approach separating genuine innovation from hype",
      "Cross-industry experience applying emerging tech to real business problems",
      "Rapid prototyping capability — from concept to working demo in 2-4 weeks",
      "Technology-agnostic recommendations focused on business value",
    ],
    metrics: [
      { value: "25+", label: "PoCs Delivered" },
      { value: "70%", label: "PoC-to-Production Rate" },
      { value: "2-4 wk", label: "Prototype Timeline" },
      { value: "5+", label: "Tech Domains" },
    ],
    how: [
      { title: "Technology Scanning", desc: "Evaluate emerging technologies against your industry context, competitive landscape, and strategic goals." },
      { title: "Feasibility Analysis", desc: "Assess technical readiness, cost implications, talent requirements, and risk factors." },
      { title: "Proof of Concept", desc: "Build a working prototype that demonstrates value, validates assumptions, and identifies integration challenges." },
      { title: "Roadmap to Production", desc: "Scale the PoC with architecture decisions, team training, and phased rollout planning." },
    ],
    techStack: ["Solidity", "Unity", "ARKit", "TensorFlow", "Rust", "WebAssembly"],
    benefits: [
      "First-mover advantage with validated emerging technologies",
      "Reduced risk through structured experimentation",
      "Innovation culture and capability building",
      "Strategic clarity on which technologies to adopt",
    ],
    caseStudy: {
      title: "Pharmaceutical Supply Chain Blockchain Pilot",
      challenge: "A pharmaceutical company needed to comply with new track-and-trace regulations while improving supply chain visibility across 200+ global partners.",
      result: "Delivered a blockchain-based supply chain pilot tracking drugs from manufacturer to pharmacy. The PoC was approved for full production rollout, projected to save $3M annually in compliance costs.",
      metric: "$3M projected annual savings",
    },
    faq: [
      { q: "How do you decide which technologies are worth pursuing?", a: "We use a structured evaluation framework assessing technology maturity, business value, implementation complexity, and market timing. We only recommend technologies with a clear path to ROI." },
      { q: "What if the proof of concept doesn't work out?", a: "That's the point of a PoC — to learn fast and cheap. Even unsuccessful pilots deliver valuable insights. We document findings, alternative approaches, and recommendations for future consideration." },
    ],
  },
];
