"""Generate PROSYS US ICP leads batch 01 CSV — 30 buyer leads."""
import csv
from pathlib import Path

COLUMNS = [
    "name", "agency", "region", "city", "linkedin", "website", "booking_url",
    "slot", "duration", "focus", "risk", "availability", "icp_fit", "booking_note", "notes",
]

LEADS = [
    {
        "name": "Richard Browning",
        "agency": "ActiveCampaign",
        "region": "US",
        "city": "Chicago IL",
        "linkedin": "https://linkedin.com/in/richardebrowning",
        "website": "https://www.activecampaign.com",
        "booking_url": "https://www.activecampaign.com/about/contact",
        "slot": "Contact / demo request",
        "duration": "n/a",
        "focus": "SaaS marketing platform scaling AI-enabled workflows for 180K+ SMB customers",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Richard — ActiveCampaign shipping AI deeper into core workflows is exactly where teams hit the production wall: permissions, eval harnesses, and governance. PROSYS LTD helps SaaS teams move AI from pilot to production. 30 min on where deployment is stuck? No deck — easy cancel.",
        "notes": "VP Engineering ActiveCampaign. ~669 employees, Chicago. YELLOW: contact page. PRIMARY — SaaS production AI.",
    },
    {
        "name": "Christopher Lankford",
        "agency": "Pie Insurance",
        "region": "US",
        "city": "Denver CO",
        "linkedin": "https://linkedin.com/in/christopherlankford",
        "website": "https://www.pieinsurance.com",
        "booking_url": "https://www.pieinsurance.com/contact-us",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "InsurTech CTO scaling ML/AI in regulated small-business insurance",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Chris — Pie running AI/ML in production underwriting is where governance and model monitoring become board-level. PROSYS LTD deploys AI safely in regulated ops. 30 min on your next production bottleneck?",
        "notes": "CTO Pie Insurance. ~314 employees, $632M raised. PRIMARY — FinTech.",
    },
    {
        "name": "Murat Aytekin",
        "agency": "Pie Insurance",
        "region": "US",
        "city": "Denver CO",
        "linkedin": "https://linkedin.com/in/murat-aytekin-9710358",
        "website": "https://www.pieinsurance.com",
        "booking_url": "https://www.pieinsurance.com/contact-us",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Director AI/ML — model routing, eval, reliability (ex-GEICO)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Murat — GEICO-scale data science to owning AI/ML at Pie is where we help: guardrails and monitoring once policy data depends on outputs. 30 min on what breaks after the first production model ships?",
        "notes": "Director AI/ML Pie. Technical champion — coordinate with Lankford. PRIMARY.",
    },
    {
        "name": "Paul Zaich",
        "agency": "Middesk",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/pzaich",
        "website": "https://www.middesk.com",
        "booking_url": "https://www.middesk.com/contact",
        "slot": "Contact sales",
        "duration": "n/a",
        "focus": "KYB identity SaaS (YC W19) — Head of Engineering productionizing agentic AI",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Paul — Middesk publicly shipping agentic AI on your own infra is rare — governance + integration debt usually follows. PROSYS LTD hardens production AI. 30 min on what you would outsource vs keep in-house?",
        "notes": "Head of Engineering Middesk. ~118 employees. PRIMARY — FinTech/KYB.",
    },
    {
        "name": "Tommy Nicholas",
        "agency": "Alloy",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/tommynicholas",
        "website": "https://www.alloy.com",
        "booking_url": "https://www.alloy.com/contact-us",
        "slot": "Contact / demo",
        "duration": "n/a",
        "focus": "Identity/fraud orchestration for banks — CEO, agentic AI in fintech",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Tommy — your agentic AI in fintech panel is the right frame. PROSYS LTD helps teams deploy AI safely once pilots touch production data. 30 min on where customers cannot productionize agents?",
        "notes": "CEO Alloy. ~292 employees NYC. PRIMARY — FinTech.",
    },
    {
        "name": "Kimberly Tom",
        "agency": "Brooklinen",
        "region": "US",
        "city": "Brooklyn NY",
        "linkedin": "https://linkedin.com/in/kimberly-tom-14187055",
        "website": "https://www.brooklinen.com",
        "booking_url": "https://www.brooklinen.com/pages/contact-us",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "D2C CX Director — BPO + omnichannel support, AI-ready ops (~140 employees)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Kimberly — scaling BPO + in-house support with AI means triage agents need HITL and helpdesk integration before leadership trusts them. PROSYS LTD deploys secure support AI. 30 min on your highest-friction workflow?",
        "notes": "Director CX Brooklinen. PRIMARY — Tier 1 customer ops ICP.",
    },
    {
        "name": "Eric Iversen",
        "agency": "Brooklinen",
        "region": "US",
        "city": "Brooklyn NY",
        "linkedin": "https://linkedin.com/in/iverseneric",
        "website": "https://www.brooklinen.com",
        "booking_url": "https://www.brooklinen.com/pages/contact-us",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "VP Software Development — Shopify/ecommerce, internal AI automation",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Eric — AI requests from CX rarely fit a naive chatbot at $100M+ D2C scale. PROSYS LTD integrates governed AI into ecommerce stacks. 30 min on the workflow your team is asked to ship?",
        "notes": "VP Software Dev Brooklinen. Engineering entry point. PRIMARY.",
    },
    {
        "name": "Wouleta Ayele",
        "agency": "sweetgreen",
        "region": "US",
        "city": "Los Angeles CA",
        "linkedin": "https://linkedin.com/in/wouleta-ayele-5b430b63",
        "website": "https://www.sweetgreen.com",
        "booking_url": "https://investor.sweetgreen.com/contact/default.aspx",
        "slot": "Corporate contact",
        "duration": "n/a",
        "focus": "Restaurant CTO — ex-Starbucks SVP Tech; AI/ML for supply chain and field ops",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Wouleta — restaurant + supply chain AI gets hard at field scale without governance across legacy systems. PROSYS LTD deploys AI with controls and integrations. 30 min on one pilot you want in production?",
        "notes": "CTO sweetgreen. ~905 employees NYSE:SG. PRIMARY — restaurant/logistics ops.",
    },
    {
        "name": "Jason Cochran",
        "agency": "sweetgreen",
        "region": "US",
        "city": "Los Angeles CA",
        "linkedin": "https://linkedin.com/in/jason-cochran-mba-a7272a3",
        "website": "https://www.sweetgreen.com",
        "booking_url": "https://investor.sweetgreen.com/contact/default.aspx",
        "slot": "Corporate contact",
        "duration": "n/a",
        "focus": "COO — field ops and innovation; ex-Chipotle VP Ops",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Jason — ops AI pilots die in the field unless wired into restaurant workflows with human oversight. PROSYS LTD builds production ops AI. 30 min on fastest-payback workflow?",
        "notes": "COO sweetgreen since 2025. Ex-Chipotle. PRIMARY.",
    },
    {
        "name": "Jacob Radkiewicz",
        "agency": "ShipBob",
        "region": "US",
        "city": "Chicago IL",
        "linkedin": "https://linkedin.com/in/jacobradkiewicz",
        "website": "https://www.shipbob.com",
        "booking_url": "https://www.shipbob.com/contact/",
        "slot": "Intro.co 1:1",
        "duration": "30m",
        "focus": "Fulfillment CTO — logistics AI, WMS/ERP integrations (~900 employees)",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Jacob — saw your Intro 1:1 sessions. Fulfillment AI must integrate with WMS/ERP or stay a demo. PROSYS LTD connects AI to operational systems safely. 30 min on your 2026 AI roadmap?",
        "notes": "CTO ShipBob. GREEN: Intro.co via LinkedIn. PRIMARY — logistics.",
    },
    {
        "name": "Judy Cochran",
        "agency": "FisherBroyles LLP",
        "region": "US",
        "city": "Atlanta GA",
        "linkedin": "https://linkedin.com/in/judycochran",
        "website": "https://www.fisherbroyles.com",
        "booking_url": "https://www.fisherbroyles.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Law firm COO — technology stack, knowledge systems, ~300 partners",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Judy — FisherBroyles Law Firm 2.0 needs permission-aware knowledge AI next. PROSYS LTD builds secure RAG with citations and access controls. 30 min on where AI search is stuck?",
        "notes": "COO FisherBroyles. VERIFY LinkedIn slug. PRIMARY — legal/professional services.",
    },
    {
        "name": "Kevin Broyles",
        "agency": "FisherBroyles LLP",
        "region": "US",
        "city": "Atlanta GA",
        "linkedin": "https://linkedin.com/in/kevin-broyles-a1b1a63",
        "website": "https://www.fisherbroyles.com",
        "booking_url": "https://www.fisherbroyles.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Managing Partner — legal innovation and technology-enabled distributed firm",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Kevin — governed AI inside matter workflows is the next legal innovation wave. PROSYS LTD deploys permission-aware knowledge systems. 30 min on partner demand for production AI?",
        "notes": "Co-founder FisherBroyles. SECONDARY — exec sponsor.",
    },
    {
        "name": "Will Gaus",
        "agency": "Troutman Pepper Locke",
        "region": "US",
        "city": "Chicago IL",
        "linkedin": "https://linkedin.com/in/will-gaus-52131b1",
        "website": "https://www.troutman.com",
        "booking_url": "https://www.troutman.com/contact/",
        "slot": "Contact professional",
        "duration": "n/a",
        "focus": "Chief KM & Innovation — Athena AI agent + Thomson Reuters Deep Research",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Will — Deep Research inside Athena is production enterprise AI — control layers and auditability are what we build. PROSYS LTD helps professional services scale governed agents. 30 min on Athena's gaps before firmwide rollout?",
        "notes": "CKMIO Troutman. ~1,700 attorneys. SECONDARY — large legal.",
    },
    {
        "name": "Waseem Daher",
        "agency": "Pilot",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/waseemdaher",
        "website": "https://pilot.com",
        "booking_url": "https://pilot.com/contact",
        "slot": "Contact / sales",
        "duration": "n/a",
        "focus": "Bookkeeping/CFO services CEO — AI in financial ops (ex-Dropbox)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Waseem — Pilot's financial data is perfect for governed automation — permissions, audit trails, human review on sensitive actions. PROSYS LTD deploys agents into financial ops. 30 min on your next AI workflow?",
        "notes": "CEO Pilot.com. MIT founder. PRIMARY — FinTech ops.",
    },
    {
        "name": "Prashant Samant",
        "agency": "Akido Labs",
        "region": "US",
        "city": "Los Angeles CA",
        "linkedin": "https://linkedin.com/in/prashantsamant",
        "website": "https://www.akidolabs.com",
        "booking_url": "https://www.akidolabs.com/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "HealthTech CEO — AI-native health system, PHI-aware clinical ops",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Prashant — AI-native health systems need PHI boundaries, human oversight, and auditability. PROSYS LTD builds governed health ops AI. 30 min on what still fails compliance review?",
        "notes": "CEO Akido Labs. ~109 employees LA. PRIMARY — HealthTech.",
    },
    {
        "name": "Gwyn Dylan Krueger",
        "agency": "Fi",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/gdk12",
        "website": "https://fi.com",
        "booking_url": "https://fi.com/pages/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "VP Customer Success — ex-Meetup VP CX; AI for support ops",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Gwyn — your Meetup CX maturation story is the stuck-at-pilot pattern: triage agents need HITL before scale. PROSYS LTD deploys secure support AI. 30 min on Fi CX automation plans?",
        "notes": "VP CS at Fi. Ex-Meetup VP CX. PRIMARY — customer ops.",
    },
    {
        "name": "Amy Merrill",
        "agency": "PartnerHero",
        "region": "US",
        "city": "Boise ID",
        "linkedin": "https://linkedin.com/in/amy-merrill-1141b529",
        "website": "https://www.partnerhero.com",
        "booking_url": "https://pages.partnerhero.com/cx-support-services",
        "slot": "Solution designer call",
        "duration": "n/a",
        "focus": "SVP Operations — BPO deploying Crescendo Augmented AI for brand clients",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Amy — Augmented AI at BPO scale needs per-client governance and QA. PROSYS LTD builds control layers for deployed agents. 30 min on where client AI fails review?",
        "notes": "SVP Ops PartnerHero/Crescendo. PRIMARY — BPO operator.",
    },
    {
        "name": "Dominic Kwok",
        "agency": "Heron Data",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/dominic-kwok-heron",
        "website": "https://www.herondata.io",
        "booking_url": "https://www.herondata.io/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "FinTech CTO — document automation; agentic engineering (YC)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Dom — Heron Hoppers show serious velocity — we add governance before agents touch client pipelines. PROSYS LTD hardens production finance AI. 30 min builder swap?",
        "notes": "CTO Heron Data. VERIFY LinkedIn URL. ~50 employees. PRIMARY.",
    },
    {
        "name": "Johannes Jaeckle",
        "agency": "Heron Data",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/johannes-jaeckle/en",
        "website": "https://www.herondata.io",
        "booking_url": "https://www.herondata.io/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "CEO — document workflows for lenders, carriers, MGAs",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Johannes — carrier/MGA doc automation scales with permission-aware retrieval and audit logs. PROSYS LTD deploys secure doc AI. 30 min on production controls customers still need?",
        "notes": "CEO Heron Data. SECONDARY — same account as Dominic.",
    },
    {
        "name": "Aidan Dewar",
        "agency": "Nourish",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/aidandewar",
        "website": "https://www.usenourish.com",
        "booking_url": "https://www.usenourish.com/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Telehealth nutrition CEO — $100M Series C; patient ops and billing AI",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Aidan — congrats on Series C. Telehealth AI needs PHI-aware controls and human review. PROSYS LTD deploys health ops AI safely. 30 min on highest-ROI ops workflow?",
        "notes": "CEO Nourish. PRIMARY — HealthTech.",
    },
    {
        "name": "Stephanie Liu",
        "agency": "Nourish",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/stephaniehliu",
        "website": "https://www.usenourish.com",
        "booking_url": "https://www.usenourish.com/contact",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Co-founder & CTO — production AI for telehealth (ex-Ethos, Instagram)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Stephanie — post-Series C, which AI features survive compliance vs stay in demo? PROSYS LTD productionizes healthtech AI with governance. 30 min technical chat?",
        "notes": "CTO Nourish. PRIMARY — technical champion.",
    },
    {
        "name": "Hal Walsh",
        "agency": "SymmetryRx",
        "region": "US",
        "city": "Radnor PA",
        "linkedin": "https://linkedin.com/in/halwalsh",
        "website": "https://www.symmetryrx.com",
        "booking_url": "https://www.symmetryrx.com/contact",
        "slot": "Phone / contact",
        "duration": "n/a",
        "focus": "Pharma SaaS CEO — eSample platform, call center, regulated ops (~8 employees)",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Hal — eSample + call center ops is where AI triage needs audit trails before pharma clients sign off. PROSYS LTD deploys governed AI in regulated ops. 30 min on AI in SampleCenter roadmap?",
        "notes": "CEO SymmetryRx. Small mid-market. GREEN: reachable CEO. PRIMARY.",
    },
    {
        "name": "Florian Otto",
        "agency": "Cedar",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/florianotto",
        "website": "https://www.cedar.com",
        "booking_url": "https://www.cedar.com/contact/",
        "slot": "Contact / demo",
        "duration": "n/a",
        "focus": "Healthcare fintech CEO — patient billing, PHI-sensitive workflows",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Florian — healthcare fintech AI needs strict data boundaries and auditability. PROSYS LTD builds production AI for regulated workflows. 30 min on compliance vs technology blockers?",
        "notes": "CEO Cedar. Ex-Zocdoc. SECONDARY — larger health fintech.",
    },
    {
        "name": "Chris Ronzio",
        "agency": "Trainual",
        "region": "US",
        "city": "Tempe AZ",
        "linkedin": "https://linkedin.com/in/chrisronzio",
        "website": "https://trainual.com",
        "booking_url": "https://trainual.com/demo",
        "slot": "Book a demo",
        "duration": "n/a",
        "focus": "SMB ops/training SaaS CEO — SOPs, internal AI for scaling teams",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Chris — next step after SOPs is AI agents that follow them in production with permissions and logging. PROSYS LTD connects governed agents to ops tools. 30 min on customer AI requests you will not ship without controls?",
        "notes": "CEO Trainual. ~116 employees. SECONDARY.",
    },
    {
        "name": "Kyle Mack",
        "agency": "Middesk",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/kyle-mack-587bbb4b",
        "website": "https://www.middesk.com",
        "booking_url": "https://www.middesk.com/contact",
        "slot": "Contact sales",
        "duration": "n/a",
        "focus": "KYB platform CEO (YC W19) — agentic AI in compliance workflows",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Kyle — agentic AI in KYB needs production governance before enterprise clients trust it. PROSYS LTD helps close that gap. 30 min founder chat?",
        "notes": "CEO Middesk. SECONDARY — same co as Paul Zaich.",
    },
    {
        "name": "Alex Timm",
        "agency": "Root Insurance",
        "region": "US",
        "city": "Columbus OH",
        "linkedin": "https://linkedin.com/in/alex-timm-b2371a16",
        "website": "https://www.joinroot.com",
        "booking_url": "https://www.joinroot.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "InsurTech CEO — telematics AI, public company (~818 employees)",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Alex — governed agents in claims and ops is the next production AI layer for insurtech. PROSYS LTD deploys AI with audit trails. 30 min if useful?",
        "notes": "CEO Root. Public. SECONDARY — larger, longer cycle.",
    },
    {
        "name": "Peter Colis",
        "agency": "Ethos Life",
        "region": "US",
        "city": "Austin TX",
        "linkedin": "https://linkedin.com/in/petercolis",
        "website": "https://www.ethos.com",
        "booking_url": "https://www.ethos.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Online life insurance CEO — AI in underwriting and customer ops",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Peter — production AI in life insurance underwriting needs the control layer most insurtechs skip. PROSYS LTD deploys governed AI. Worth 30 min?",
        "notes": "CEO Ethos. ~635 employees Austin. SECONDARY.",
    },
    {
        "name": "Spencer Starley",
        "agency": "Udemy",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/spencerstarley",
        "website": "https://www.udemy.com",
        "booking_url": "https://about.udemy.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Sr. Director Client Experience & Support Ops — Crescendo/PartnerHero client",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Spencer — PartnerHero quoted you on scaling CX with AI backup — we implement that pattern with governance and HITL. PROSYS LTD deploys secure support AI. 30 min on Udemy's support AI roadmap?",
        "notes": "PartnerHero testimonial. VERIFY current role/LinkedIn before outreach. PRIMARY.",
    },
    {
        "name": "Ines Elyseu",
        "agency": "Khan Academy",
        "region": "US",
        "city": "Mountain View CA",
        "linkedin": "https://linkedin.com/in/ineselyseu",
        "website": "https://www.khanacademy.org",
        "booking_url": "https://www.khanacademy.org/about",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Manager Customer Support — edtech CX at scale, augmented AI client",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Ines — learner support AI needs governed responses, not hallucinated tutoring. PROSYS LTD deploys support AI with QA and escalation. 30 min on your AI support stack?",
        "notes": "PartnerHero testimonial Khan Academy. VERIFY LinkedIn. PRIMARY — edtech CX.",
    },
    {
        "name": "James M. Fisher II",
        "agency": "FisherBroyles LLP",
        "region": "US",
        "city": "Atlanta GA",
        "linkedin": "https://linkedin.com/in/jamfish",
        "website": "https://www.fisherbroyles.com",
        "booking_url": "https://www.fisherbroyles.com/contact/",
        "slot": "Contact form",
        "duration": "n/a",
        "focus": "Founder & Managing Partner — distributed law firm, legal tech and innovation",
        "risk": "yellow",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey James — FisherBroyles disrupted BigLaw with Law Firm 2.0; governed AI for matter knowledge is the next layer. PROSYS LTD builds secure legal knowledge systems. 30 min on partner AI demand?",
        "notes": "Co-founder FisherBroyles. AmLaw 200. SECONDARY — exec sponsor alongside Judy/Kevin.",
    },
]

assert len(LEADS) == 30, f"Expected 30 leads, got {len(LEADS)}"

out = Path(__file__).parent / "prosys_us_icp_leads_batch01.csv"
with out.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=COLUMNS, quoting=csv.QUOTE_MINIMAL)
    writer.writeheader()
    writer.writerows(LEADS)

print(f"Wrote {len(LEADS)} leads to {out}")
