"""Generate PROSYS US ICP leads batch 02 — cal.com / Calendly booking URLs only."""
import csv
from pathlib import Path

COLUMNS = [
    "name", "agency", "region", "city", "linkedin", "website", "booking_url",
    "slot", "duration", "focus", "risk", "availability", "icp_fit", "booking_note", "notes",
]

# Excluded: all 30 contacts from prosys_us_icp_leads_batch01.csv
BATCH01_NAMES = {
    "Richard Browning", "Christopher Lankford", "Murat Aytekin", "Paul Zaich",
    "Tommy Nicholas", "Kimberly Tom", "Eric Iversen", "Wouleta Ayele", "Jason Cochran",
    "Jacob Radkiewicz", "Judy Cochran", "Kevin Broyles", "Will Gaus", "Waseem Daher",
    "Prashant Samant", "Gwyn Dylan Krueger", "Amy Merrill", "Dominic Kwok",
    "Johannes Jaeckle", "Aidan Dewar", "Stephanie Liu", "Hal Walsh", "Florian Otto",
    "Chris Ronzio", "Kyle Mack", "Alex Timm", "Peter Colis", "Spencer Starley",
    "Ines Elyseu", "James M. Fisher II",
}

LEADS = [
    {
        "name": "Richard Meng",
        "agency": "ROE AI",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/richard-meng-roe",
        "website": "https://www.getroe.ai",
        "booking_url": "https://cal.com/richard-meng/startup-advice",
        "slot": "Startup advice",
        "duration": "20m",
        "focus": "YC-backed auditable AI investigators for fraud, KYC/AML, and compliance ops",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Richard — Roe shipping auditable investigators into BNPL and bank ops is exactly where production AI hits governance walls. PROSYS LTD helps teams deploy AI safely with evidence trails and human oversight. 20 min on what breaks after the first agent goes live?",
        "notes": "CEO ROE AI (YC, Gradient, Snowflake). GREEN: cal.com startup-advice. PRIMARY — FinTech compliance ops.",
    },
    {
        "name": "Shawn-Marc Melo",
        "agency": "deepidv",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/shawnmarcmelo",
        "website": "https://www.deepidv.com",
        "booking_url": "https://cal.com/shawn-marc-melo-wsvtoa/discovery-call",
        "slot": "Discovery Call",
        "duration": "30m",
        "focus": "AI-native fraud SDKs, KYC/AML, and agentic identity monitoring for FinTech",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Shawn-Marc — deepidv's agentic monitoring stack is where production identity AI needs guardrails before enterprise clients trust it. PROSYS LTD hardens governed AI in regulated onboarding. 30 min builder chat?",
        "notes": "Founder & CEO deepidv. GREEN: cal.com discovery-call. PRIMARY — FinTech fraud/KYC.",
    },
    {
        "name": "Ray Ventura",
        "agency": "1099Policy",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/ray-ventura",
        "website": "https://www.1099policy.com",
        "booking_url": "https://cal.com/ray-ventura/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "InsurTech CTO — contractor insurance platform, regulated policy workflows",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Ray — 1099Policy scaling AI in insurance ops is where audit trails and integration debt show up fast. PROSYS LTD deploys production AI with controls in insurtech. 15 min on your next production bottleneck?",
        "notes": "CTO & co-founder 1099Policy. GREEN: cal.com/15min. PRIMARY — InsurTech.",
    },
    {
        "name": "Mark Bilodeau",
        "agency": "Policy Pulse",
        "region": "US",
        "city": "Boston MA",
        "linkedin": "https://linkedin.com/in/markbilodeau",
        "website": "https://www.policypulse.com",
        "booking_url": "https://cal.com/mark.policypulse/30min",
        "slot": "Demo (30 min)",
        "duration": "30m",
        "focus": "InsurTech CTO — policy intelligence and carrier workflow automation",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Mark — policy workflow AI needs governed outputs before carriers sign off. PROSYS LTD builds production AI with auditability for regulated insurance ops. Worth 30 min on Policy Pulse's deployment gaps?",
        "notes": "CTO Policy Pulse. GREEN: cal.com demo 30m. PRIMARY — InsurTech.",
    },
    {
        "name": "Will Pedley",
        "agency": "Compliance Circle",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/willpedley",
        "website": "https://www.compliancecircle.com",
        "booking_url": "https://cal.com/will-pedley/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Compliance ops CEO — regulated business systems and audit readiness",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Will — compliance teams automating with AI need attestable controls, not another chatbot. PROSYS LTD deploys governed agents into regulated ops. 15 min on where clients get stuck post-pilot?",
        "notes": "CEO Compliance Circle. GREEN: cal.com/15min. PRIMARY — compliance ops.",
    },
    {
        "name": "Eric Rosenblum",
        "agency": "Magnum Software Services",
        "region": "US",
        "city": "Oceanside CA",
        "linkedin": "https://linkedin.com/in/eric-rosenblum-magnum",
        "website": "https://magnumsoftwareservices.com",
        "booking_url": "https://cal.com/magnumsoftwareservices/15min",
        "slot": "15 min meeting",
        "duration": "15m",
        "focus": "Insurance distribution software — MGA/agency quote-to-cash and legacy migration",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Eric — quote-to-cash AI for MGAs breaks on rating logic and audit trails, not demos. PROSYS LTD productionizes governed AI in insurance distribution. 15 min builder swap?",
        "notes": "Founder Magnum Software Services. GREEN: cal.com/15min. PRIMARY — insurance distribution.",
    },
    {
        "name": "Adil Hussain Mughal",
        "agency": "Ranea AI",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/adil-hussain-mughal",
        "website": "https://www.ranea.ai",
        "booking_url": "https://cal.com/ranea.ai/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "HealthTech CEO — vertical AI agents for clinic ops, EHR, and insurance verification",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Adil — clinic agents touching PHI need HITL and audit logs before scale. PROSYS LTD deploys governed health ops AI. 15 min on what still fails compliance review?",
        "notes": "Founder & CEO Ranea AI. GREEN: cal.com/15min. PRIMARY — HealthTech ops.",
    },
    {
        "name": "John De Bellis",
        "agency": "Digital Thinking / Medsyntra",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/johndebellis",
        "website": "https://www.medsyntra.com",
        "booking_url": "https://cal.com/medsyntra/15min",
        "slot": "15 min meeting",
        "duration": "15m",
        "focus": "Healthcare + legal AI CEO — voice, scheduling, compliance, and practice ops",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey John — Medsyntra + Counsel AI bridging clinical and legal workflows is where governance layers matter. PROSYS LTD deploys production AI with PHI and privilege controls. 15 min?",
        "notes": "CEO Digital Thinking (Medsyntra, Counsel AI). GREEN: cal.com/medsyntra/15min. PRIMARY — healthcare + legal ops.",
    },
    {
        "name": "Kyle Shechtman",
        "agency": "Acuity Health",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/kyle-shechtman",
        "website": "https://www.acuityhealth.ai",
        "booking_url": "https://cal.com/kyle-shechtman-acuity/15min",
        "slot": "15 min meeting",
        "duration": "15m",
        "focus": "HealthTech CEO — AI phone systems for medical practices",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Kyle — medical practice voice AI needs escalation paths and call audit trails before groups roll it out. PROSYS LTD builds governed support AI for regulated ops. 15 min?",
        "notes": "CEO Acuity Health. GREEN: cal.com/15min. PRIMARY — HealthTech customer ops.",
    },
    {
        "name": "Rajiv Ghanta",
        "agency": "Mimic",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/rajivghanta",
        "website": "https://www.mimic.ai",
        "booking_url": "https://cal.com/mimic/30min",
        "slot": "Mimic Meeting",
        "duration": "30m",
        "focus": "Founder — AI agents for dental and medical practice operations",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Rajiv — practice agents scheduling and triaging patients need PHI boundaries and human handoff. PROSYS LTD productionizes health ops AI safely. 30 min?",
        "notes": "Founder Mimic. GREEN: cal.com/30min. PRIMARY — HealthTech.",
    },
    {
        "name": "Arya Satish",
        "agency": "Moodr Health",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/aryasatish",
        "website": "https://www.moodrhealth.com",
        "booking_url": "https://cal.com/arya-satish/clinical-advisory",
        "slot": "Clinical Advisory",
        "duration": "15m",
        "focus": "CEO — behavioral health engagement platform for health systems and FQHCs",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Arya — behavioral health AI at health-system scale needs governed engagement and auditability. PROSYS LTD deploys production AI for regulated care ops. 15 min on deployment blockers?",
        "notes": "CEO Moodr Health. GREEN: cal.com clinical-advisory (also has product demo on profile). PRIMARY — HealthTech.",
    },
    {
        "name": "Sohum Patel",
        "agency": "Penelope Health",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/sohum-patel-md",
        "website": "https://www.penelopehealth.com",
        "booking_url": "https://cal.com/sohum-patel/30min",
        "slot": "30 Min Meeting",
        "duration": "30m",
        "focus": "Physician-founder — healthtech platform for clinical and practice operations",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Sohum — physician-led healthtech AI needs clinical oversight baked into production, not bolted on. PROSYS LTD builds governed health ops agents. 30 min?",
        "notes": "Founder Penelope Health. GREEN: cal.com/30min. PRIMARY — HealthTech.",
    },
    {
        "name": "Gus Neate",
        "agency": "Claren",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/gus-neate",
        "website": "https://www.claren.ai",
        "booking_url": "https://cal.com/gus-neate-claren/zoom-catch-up",
        "slot": "Zoom catch up",
        "duration": "30m",
        "focus": "Legal tech CEO — AI for law firm knowledge and workflow automation",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Gus — legal AI that touches matter data needs permission-aware retrieval and citations before firmwide rollout. PROSYS LTD builds secure knowledge systems for professional services. 30 min?",
        "notes": "Co-founder & CEO Claren. GREEN: cal.com zoom-catch-up. PRIMARY — legal tech.",
    },
    {
        "name": "Kevin Xie",
        "agency": "Soren AI",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/kevin-xie-soren",
        "website": "https://www.soren-ai.com",
        "booking_url": "https://cal.com/kevin-soren-ai/demo",
        "slot": "Demo",
        "duration": "30m",
        "focus": "YC F25 legal AI CEO — enterprise tools for law firms (ex-MIT)",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Kevin — Soren deploying into law firm workflows is where privilege, citations, and human review become non-negotiable. PROSYS LTD hardens production legal AI. 30 min founder chat?",
        "notes": "Founder & CEO Soren AI (YC F25). GREEN: cal.com/demo. PRIMARY — legal tech.",
    },
    {
        "name": "Vanessa Schlenz",
        "agency": "Finium Legal",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/vanessa-schlenz",
        "website": "https://www.finiumlegal.com",
        "booking_url": "https://cal.com/vanessa-schlenz-bx4u1n/finium-legal-intro-15-min",
        "slot": "Finium Legal - Intro 15 min",
        "duration": "15m",
        "focus": "Legal tech founder — AI for financial and legal operations",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Vanessa — Finium's regulated legal-finance workflows need governed AI before clients trust automation. PROSYS LTD deploys secure agents in professional services. 15 min?",
        "notes": "Founder & CEO Finium Legal. GREEN: cal.com intro 15m. PRIMARY — legal/fintech.",
    },
    {
        "name": "Silvestre Jara Montes",
        "agency": "Traza",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/silvestre-jara-montes",
        "website": "https://www.traza.ai",
        "booking_url": "https://cal.com/silver-traza/15-with-silvestre-co-founder-at-traza",
        "slot": "15' with Silvestre - Co-Founder at Traza",
        "duration": "15m",
        "focus": "CEO — AI workers for supply chain procurement and RFQ automation",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Silvestre — procurement agents touching ERP and supplier data need governance before enterprise rollout. PROSYS LTD connects production AI to ops systems safely. 15 min?",
        "notes": "CEO Traza (Base10, pre-seed). GREEN: cal.com 15m slot. PRIMARY — supply chain ops.",
    },
    {
        "name": "Hari Subramanian",
        "agency": "Niti AI",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/harisubramanian",
        "website": "https://www.nitiai.com",
        "booking_url": "https://cal.com/nitiai/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "CEO — customer engagement AI; ex-Uber VP eng for support tech stack",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Hari — after Uber-scale support infra, Niti's CX AI needs HITL and QA layers before enterprise buyers trust it. PROSYS LTD deploys governed support AI. 15 min?",
        "notes": "CEO Niti AI. Ex-Uber Customer Obsession Engineering. GREEN: cal.com/15min. PRIMARY — customer ops.",
    },
    {
        "name": "Romeo Bellon",
        "agency": "Receiptor AI",
        "region": "US",
        "city": "Newark DE",
        "linkedin": "https://linkedin.com/in/romeo-bellon",
        "website": "https://receiptor.ai",
        "booking_url": "https://cal.com/romeo-bellon/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Founder — AI bookkeeping automation from email receipts and invoices",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Romeo — bookkeeping AI touching client financial data needs permissions and audit trails, not just extraction accuracy. PROSYS LTD hardens production finance ops AI. 15 min?",
        "notes": "Founder Receiptor AI (US HQ Newark DE). GREEN: cal.com/15min. PRIMARY — FinTech ops.",
    },
    {
        "name": "Hemant Gangolia",
        "agency": "Rally Tax",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/hemantgangolia",
        "website": "https://www.rally.tax",
        "booking_url": "https://cal.com/hemant-rally/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "YC-backed tax/fintech CEO — AI in financial and tax operations",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Hemant — tax ops AI needs strict data boundaries and human review on sensitive filings. PROSYS LTD deploys governed agents in financial ops. 15 min?",
        "notes": "Founder & CEO Rally Tax (YC). GREEN: cal.com/15min. PRIMARY — FinTech.",
    },
    {
        "name": "Kieran Taylor",
        "agency": "Midship",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/kieranctaylor",
        "website": "https://midship.ai",
        "booking_url": "https://cal.com/kieran-midship/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Co-founder — AI agents for SOX testing and audit workpapers (YC, acquired by Optro)",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Kieran — SOX agents producing auditor-reliable workpapers is production AI with zero margin for hallucination. PROSYS LTD builds governed agents for regulated workflows. 15 min?",
        "notes": "Co-founder Midship (YC, Optro). GREEN: cal.com/15min. PRIMARY — audit/compliance ops.",
    },
    {
        "name": "Silvia Chen",
        "agency": "Bilrost",
        "region": "US",
        "city": "Miami FL",
        "linkedin": "https://linkedin.com/in/silviachen",
        "website": "https://www.bilrost.ai",
        "booking_url": "https://cal.com/silvia-chen-bilrost/30min",
        "slot": "30 Min Meeting",
        "duration": "30m",
        "focus": "CEO — AI loan processing and document automation for RTL/DSCR lenders",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Silvia — lender doc AI must validate extraction and keep audit trails before underwriting trusts outputs. PROSYS LTD productionizes governed doc AI. 30 min?",
        "notes": "CEO Bilrost. GREEN: cal.com/30min. PRIMARY — lending/doc automation.",
    },
    {
        "name": "Shaun Wei",
        "agency": "Hey Revia",
        "region": "US",
        "city": "San Francisco CA",
        "linkedin": "https://linkedin.com/in/shaunwei",
        "website": "https://heyrevia.ai",
        "booking_url": "https://calendly.com/shaunagi/30min",
        "slot": "30 min meeting",
        "duration": "30m",
        "focus": "YC CEO — HIPAA voice AI automating healthcare admin calls (prior auth, billing)",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Shaun — Revia replacing BPO phone ops needs HIPAA guardrails, QA, and escalation paths at scale. PROSYS LTD deploys governed voice AI in regulated ops. 30 min?",
        "notes": "CEO Hey Revia (YC). GREEN: calendly.com/shaunagi/30min. PRIMARY — healthcare BPO/voice ops.",
    },
    {
        "name": "Anthony Hunter",
        "agency": "Nexaira",
        "region": "US",
        "city": "Atlanta GA",
        "linkedin": "https://linkedin.com/in/anthony-hunter-nexaira",
        "website": "https://nexaira.com",
        "booking_url": "https://cal.com/ahunter",
        "slot": "Founder Alignment Call (Start Here)",
        "duration": "15m",
        "focus": "SMB ops redesign + AI systems implementation for scaling operators",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Anthony — your 'restructure ops before automating chaos' line matches where PROSYS clients get stuck. We deploy governed AI into real workflows with controls and integrations. Booked the Founder Alignment 15m — easy cancel.",
        "notes": "Founder Nexaira (Atlanta). GREEN: cal.com/ahunter — select Founder Alignment Call 15m on page. PRIMARY — SMB ops AI.",
    },
    {
        "name": "Jefferson G. Sanchez",
        "agency": "Bimrock AI",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/jeffersonsanchez",
        "website": "https://www.bimrock.ai",
        "booking_url": "https://cal.com/jefferson-g-sanchez/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Co-founder — automated MEP design AI for construction and AEC workflows",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Jefferson — MEP design AI in production needs engineering review loops and version control, not just generation speed. PROSYS LTD builds governed ops AI for complex workflows. 15 min?",
        "notes": "Co-founder Bimrock AI (MIT). GREEN: cal.com/15min. PRIMARY — construction ops.",
    },
    {
        "name": "Jacky Chen",
        "agency": "Roostr AI",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/jacky-chen-roostr",
        "website": "https://www.roostr.ai",
        "booking_url": "https://cal.com/jacky-chen-roostr/on-call",
        "slot": "on call",
        "duration": "30m",
        "focus": "Founder CEO — AI-native 4PL logistics and fulfillment operations",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "primary",
        "booking_note": "Hey Jacky — 4PL AI must integrate with WMS/TMS or stay a dashboard. PROSYS LTD connects production agents to logistics systems with oversight. 30 min on your ops AI roadmap?",
        "notes": "CEO Roostr AI (ShipRoostr). GREEN: cal.com on-call. PRIMARY — logistics ops.",
    },
    {
        "name": "Ajay Krishnan",
        "agency": "Ajay Krishnan (Legal AI)",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/ajayk",
        "website": "https://cal.com/ajayk",
        "booking_url": "https://cal.com/ajayk/30min",
        "slot": "30 Min Meeting",
        "duration": "30m",
        "focus": "Lawyer-engineer building AI lawyer integrated with Google Drive",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Ajay — permission-aware legal AI in Drive needs audit trails before firms trust it firmwide. PROSYS LTD builds secure knowledge AI for professional services. 30 min?",
        "notes": "Lawyer who codes. GREEN: cal.com/30min. SECONDARY — solo builder.",
    },
    {
        "name": "Charles Denyer",
        "agency": "Compliance Security Academy",
        "region": "US",
        "city": "United States",
        "linkedin": "https://linkedin.com/in/charlesdenyer",
        "website": "https://www.compliancesecurityacademy.com",
        "booking_url": "https://cal.com/charlesdenyer/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Security & compliance advisor — CMMC, NIST RMF, audit readiness for high-growth cos",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Charles — clients asking for AI in compliance workflows need governed deployment, not shadow IT pilots. PROSYS LTD helps operators ship AI with auditability. 15 min?",
        "notes": "Compliance Security Academy. GREEN: cal.com/15min. SECONDARY — advisory/compliance.",
    },
    {
        "name": "Alex Bushe",
        "agency": "Fuller Focus AI",
        "region": "US",
        "city": "Atlanta GA",
        "linkedin": "https://linkedin.com/in/alex-bushe-fullerfocus",
        "website": "https://www.fullerfocus.ai",
        "booking_url": "https://cal.com/alex-fullerfocus/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "CEO — AI sales intelligence for teams selling to nonprofits",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Alex — nonprofit sales AI still needs data governance and human review before teams trust outreach automation. PROSYS LTD productionizes governed GTM AI. 15 min?",
        "notes": "Co-founder & CEO Fuller Focus AI. GREEN: cal.com/15min. SECONDARY — SaaS GTM.",
    },
    {
        "name": "Prasad Bhalerao",
        "agency": "CFOLogic",
        "region": "US",
        "city": "Sacramento CA",
        "linkedin": "https://linkedin.com/in/growthcfo",
        "website": "https://www.cfologic.com",
        "booking_url": "https://cal.com/growthcfo/15min",
        "slot": "15 Min Meeting",
        "duration": "15m",
        "focus": "Fractional CFO — FinOps, FP&A, and financial automation for funded startups",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Prasad — portfolio clients asking for AI in finance ops need controls before automating approvals. PROSYS LTD deploys governed agents in financial workflows. 15 min?",
        "notes": "Founder CFOLogic (US entity Sacramento). GREEN: cal.com/15min. SECONDARY — FinOps services.",
    },
    {
        "name": "Farrah Fogarty",
        "agency": "New Era AI Consulting",
        "region": "US",
        "city": "New York NY",
        "linkedin": "https://linkedin.com/in/farrah-fogarty-996b61a",
        "website": "https://www.neweraaiconsulting.com",
        "booking_url": "https://cal.com/farrah-fogarty-8uxomb/15min",
        "slot": "15 min meeting",
        "duration": "15m",
        "focus": "SVP AI strategist (Citi) + enterprise AI transformation consulting",
        "risk": "green",
        "availability": "n/a",
        "icp_fit": "secondary",
        "booking_note": "Hey Farrah — enterprise AI transformation past the pilot deck needs production governance and integration. PROSYS LTD helps operators deploy AI safely in regulated workflows. 15 min peer chat?",
        "notes": "SVP AI @ Citi + New Era AI Consulting. GREEN: cal.com/15min. SECONDARY — enterprise operator.",
    },
]


def main() -> None:
    assert len(LEADS) == 30, f"Expected 30 leads, got {len(LEADS)}"
    names = [lead["name"] for lead in LEADS]
    assert len(names) == len(set(names)), "Duplicate names in batch 02"
    overlap = set(names) & BATCH01_NAMES
    assert not overlap, f"Batch01 overlap: {overlap}"
    agencies = [lead["agency"] for lead in LEADS]
    assert len(agencies) == len(set(agencies)), "Duplicate agencies in batch 02"

    for lead in LEADS:
        url = lead["booking_url"]
        assert "cal.com" in url or "calendly.com" in url, f"Invalid booking URL: {url}"
        assert lead["risk"] == "green", f"All leads must be green (cal/calendly): {lead['name']}"

    out = Path(__file__).resolve().parent / "prosys_us_icp_leads_batch02.csv"
    with out.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS, extrasaction="ignore")
        w.writeheader()
        w.writerows(LEADS)
    print(f"Wrote {len(LEADS)} leads to {out}")


if __name__ == "__main__":
    main()
